Repository Apicurio/apicurio-registry, pull requests merged in 2020-05, with the labels that each got.

#399 Implement JSON Schema compatibility rule. Fixes #373
  app/pom.xml
  app/src/main/java/io/apicurio/registry/rules/compatibility/JsonCompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonSchemaDiffLibrary.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonSchemaWrapperVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonUtil.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ArraySchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/BooleanSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/CombinedSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ConditionalSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ConstSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffContext.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffType.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffUtil.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/Difference.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/EnumSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/NotSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/NullSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/NumberSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ObjectSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/PrimitiveSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ReferenceSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/SchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/StringSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ArraySchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/BooleanSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/CombinedSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ConditionalSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ConstSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/EmptySchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/EnumSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/FalseSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/NotSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/NullSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/NumberSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ObjectSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ReferenceSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/SchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/StringSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/TrueSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/WrapUtil.java
  app/src/test/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonSchemaSmokeTest.java
  app/src/test/resources/io/apicurio/registry/rules/compatibility/jsonschema/compatibility-test-data.json
  pom.xml
Labels: Enhancement

#461 Some simple renames
  app/src/test/java/io/apicurio/registry/SerdeMixTest.java
  utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaSerDe.java
  utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy/Legacy4ByteIdHandler.java
Labels: Task

#460 Code modifications to reduce the # of compile warnings
  app/src/main/java/io/apicurio/registry/ccompat/rest/error/ConflictException.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/BooleanSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ObjectSchemaDiffVisitor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ObjectSchemaWrapper.java
  app/src/main/java/io/apicurio/registry/rules/validity/JsonSchemaContentValidator.java
  app/src/test/java/io/apicurio/registry/JsonConverterTest.java
  app/src/test/java/io/apicurio/registry/JsonSerdeTest.java
  app/src/test/java/io/apicurio/registry/RegistrySerdeTest.java
  app/src/test/java/io/apicurio/registry/SerdeMixTest.java
  app/src/test/java/io/apicurio/registry/rules/validity/JsonSchemaContentValidatorTest.java
  app/src/test/java/io/confluent/connect/avro/AvroData.java
  search/client/src/main/java/io/apicurio/registry/search/client/hotrod/ArtifactMarshaller.java
  tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/DownloadRegistryMojo.java
Labels: Quality

#479 [registry][fixes] Add cleanup, fix connection for Confluent client
  tests/src/test/java/io/apicurio/tests/BaseIT.java
  tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java
Labels: Bug
