Repository Apicurio/apicurio-registry, pull requests merged in 2020-11, with the labels that each got.

#971 Add Datum and Protobuf docs.
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-types.adoc
Labels: Documentation

#981 Removed the kafka storage variant
  .github/workflows/integration-tests.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  distro/docker/pom.xml
  pom.xml
  storage/kafka/pom.xml
  storage/kafka/src/main/assembly/assembly.xml
  storage/kafka/src/main/java/io/apicurio/registry/kafka/KafkaRegistryConfiguration.java
  storage/kafka/src/main/java/io/apicurio/registry/kafka/KafkaRegistryStorage.java
  storage/kafka/src/main/java/io/apicurio/registry/kafka/KafkaRegistryStorageHandle.java
  storage/kafka/src/main/java/io/apicurio/registry/kafka/RegistryConsumerContainer.java
  storage/kafka/src/main/java/io/apicurio/registry/kafka/snapshot/StorageSnapshot.java
  storage/kafka/src/main/java/io/apicurio/registry/kafka/snapshot/StorageSnapshotSerde.java
  storage/kafka/src/main/java/io/apicurio/registry/kafka/util/CloseableSupplier.java
  storage/kafka/src/test/java/io/apicurio/registry/storage/util/KafkaServiceInitializer.java
  storage/kafka/src/test/resources/cluster-test.properties
  storage/kafka/storage_setup.sh
Labels: 2.0.x

#958 Return the list of errors that cause validity/compatibility issues
  app/src/main/java/io/apicurio/registry/rest/RegistryExceptionMapper.java
  app/src/main/java/io/apicurio/registry/rules/RuleViolationException.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/AvroCompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/CompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/CompatibilityExecutionResult.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/CompatibilityRuleExecutor.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/JsonCompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/NoopCompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/ProtobufCompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/ProtobufFdCompatibilityChecker.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonSchemaDiffLibrary.java
  app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffContext.java
  app/src/main/java/io/apicurio/registry/rules/validity/ValidityRuleExecutor.java
  app/src/test/java/io/apicurio/registry/ArtifactTypeTest.java
  app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
  app/src/test/java/io/apicurio/registry/FullApiTest.java
  app/src/test/java/io/apicurio/registry/JsonSchemas.java
  app/src/test/java/io/apicurio/registry/TestResourceTest.java
  app/src/test/java/io/apicurio/registry/compatibility/CompatibilityRuleApplicationTest.java
  app/src/test/resources/io/apicurio/registry/rules/validity/jsonschema-valid-compatible.json
  app/src/test/resources/io/apicurio/registry/rules/validity/jsonschema-valid-incompatible.json
  common/src/main/java/io/apicurio/registry/rest/beans/RuleViolationCause.java
  common/src/main/java/io/apicurio/registry/rest/beans/RuleViolationError.java
  common/src/main/resources/META-INF/openapi.json
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
  ui/packages/registry/src/app/pages/artifactVersion/artifactVersion.tsx
Labels: 2.0.x, Impacts Documentation

#985 REST Client throw specific exceptions
  app/src/main/java/io/apicurio/registry/rest/RegistryExceptionMapper.java
  app/src/test/java/io/apicurio/registry/ArtifactStateTest.java
  common/src/main/java/io/apicurio/registry/rest/beans/Error.java
  rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClient.java
  rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClientImpl.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/AlreadyExistsException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/ArtifactAlreadyExistsException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/ArtifactNotFoundException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/BadRequestException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/ConflictException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/DefaultRuleDeletionException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/InvalidArtifactStateException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/InvalidArtifactTypeException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/NotFoundException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/RestClientException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/RuleAlreadyExistsException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/RuleNotFoundException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/RuleViolationException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/UnprocessableEntityException.java
  rest-client/src/main/java/io/apicurio/registry/client/exception/VersionNotFoundException.java
  rest-client/src/main/java/io/apicurio/registry/client/request/HeadersInterceptor.java
  rest-client/src/main/java/io/apicurio/registry/client/request/RequestExecutor.java
  rest-client/src/main/java/io/apicurio/registry/client/request/RequestHandler.java
  rest-client/src/main/java/io/apicurio/registry/client/request/ResultCallback.java
  rest-client/src/main/java/io/apicurio/registry/client/response/ExceptionMapper.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/LoadIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
  tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
  tests/src/test/java/io/apicurio/tests/ui/DeleteArtifactIT.java
  utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy/AbstractCrudIdStrategy.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java
Labels: 2.0.x, Impacts Documentation
