Repository Apicurio/apicurio-registry, pull requests merged in 2022-10, with the labels that each got.

#2861 Cleanup Tenant manager staging things
  build-deploy.sh
  distro/docker/src/main/docker/Dockerfile.tenant-manager.jvm
Labels: triage/needs-triage

#2854 Fix complex array validation when field is not present
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/resources/io/apicurio/registry/util/sample.account.json
  app/src/test/resources/io/apicurio/registry/util/sample.address.json
  app/src/test/resources/io/apicurio/registry/util/sample.email.json
  app/src/test/resources/io/apicurio/registry/util/sample.phone.json
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchema.java
Labels: area/serdes

#2857 docs: updated + new security options
  docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-changing-artifact-owner-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-kafka-streams-operatorhub.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-postgresql-operatorhub.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-operatorhub.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
  docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-setting-up-postgresql-storage.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: triage/needs-triage

#2869 Remove temporary jbang folder
  .gitignore
  docs/.jbang/jbang/version.txt
Labels: triage/needs-triage

#2870 Workaround `jackson-coreutils` download issue
  .github/workflows/integration-tests.yaml
Labels: triage/needs-triage

#2871 Implement the `jackson-coreutils` workaround in more CI workflows
  .github/workflows/registry-rhbq-build.yaml
  .github/workflows/verify.yaml
Labels: triage/needs-triage

#2866 Clean the OpenShift template from Tenant Manager
  distro/openshift-template/mt/apicurio-registry-mt-template.yaml
Labels: triage/needs-triage

#2876 restore TENANT_MANAGER_AUTH_TOKEN_EXP_REDUCTION_MS
  distro/openshift-template/mt/apicurio-registry-mt-template.yaml
Labels: triage/needs-triage

#2885 Remove resources specific to mas
  Dockerfile.testing
  build-deploy.sh
  distro/openshift-template/mt/apicurio-perf-job.yaml
  distro/openshift-template/mt/apicurio-registry-mt-template.yaml
  pr-check.sh
  pr_check_docker.sh
  security-scan.sh
Labels: triage/needs-triage

#2880 Prevent slaming auth server
  app/src/main/java/io/apicurio/registry/services/auth/CustomAuthenticationMechanism.java
  app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
Labels: triage/needs-triage

#2898 Improve oas references descriptions
  app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json
Labels: triage/needs-triage

#2901 Removed the debouncer from the Upload artifact form
  ui/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx
Labels: area/ui

#2903 fix: comply with undocumented behavior in ccompat when parsing versions
  app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
  app/src/test/java/io/apicurio/registry/ccompat/rest/SubjectVersionStringTest.java
Labels: area/storage
