Repository Apicurio/apicurio-registry, pull requests merged in 2022-08, with the labels that each got.

#2693 Updated the Settings page and Artifact Properties modal
  ui/src/app/app.css
  ui/src/app/components/header/pageheader.tsx
  ui/src/app/components/ruleList/ruleList.css
  ui/src/app/components/ruleList/ruleList.tsx
  ui/src/app/pages/artifactVersion/components/modals/editMetaDataModal.tsx
  ui/src/app/pages/artifactVersion/components/modals/propertiesFormGroup.tsx
  ui/src/app/pages/artifactVersion/components/tabs/info.css
  ui/src/app/pages/artifactVersion/components/tabs/info.tsx
  ui/src/app/pages/settings/components/configProperty.css
  ui/src/app/pages/settings/components/configProperty.tsx
  ui/src/app/pages/settings/settings.css
  ui/src/app/pages/settings/settings.tsx
  ui/tslint.json
Labels: Impacts Documentation

#2660 Create artifacts from URL
  app/pom.xml
  app/src/main/java/io/apicurio/registry/rest/RestConfig.java
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/util/ArtifactTypeUtil.java
  app/src/main/java/io/apicurio/registry/util/ContentTypeUtil.java
  app/src/main/resources/application.properties
  app/src/test/java/io/apicurio/registry/ibmcompat/SchemaRegistryRestAPIClient.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
  app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java
  client/src/main/java/io/apicurio/registry/rest/client/RegistryClient.java
  client/src/main/java/io/apicurio/registry/rest/client/impl/RegistryClientImpl.java
  common/src/main/java/io/apicurio/registry/rest/Headers.java
  common/src/main/java/io/apicurio/registry/rest/v2/GroupsResource.java
  common/src/main/java/io/apicurio/registry/utils/JAXRSClientUtil.java
  common/src/main/resources/META-INF/openapi.json
  integration-tests/testsuite/src/main/java/io/apicurio/tests/LoadBalanceRegistryClient.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/RegistryUITester.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/pages/UploadArtifactDialog.java
  pom.xml
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  ui/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx
  ui/src/services/groups/groups.service.ts
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: Impacts Documentation

#2716 Fix avro nested references
  app/pom.xml
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  app/src/test/resources/io/apicurio/registry/serde/AvroSchemaA.avsc
  app/src/test/resources/io/apicurio/registry/serde/AvroSchemaB.avsc
  app/src/test/resources/io/apicurio/registry/serde/AvroSchemaC.avsc
  app/src/test/resources/io/apicurio/registry/serde/AvroSchemaD.avsc
  app/src/test/resources/io/apicurio/registry/serde/AvroSchemaE.avsc
  app/src/test/resources/io/apicurio/registry/serde/Exchange.avsc
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaParser.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaUtils.java
Labels: area/serdes

#2714 AsyncAPI Documentation Tab
  ui/package-lock.json
  ui/package.json
  ui/src/app/pages/artifactVersion/artifactVersion.tsx
  ui/src/app/pages/artifactVersion/components/tabs/documentation.tsx
  ui/webpack.common.js
Labels: area/ui

#2726 docs: clean up context IDs and versions
  docs/modules/ROOT/pages/getting-started/assembly-configuring-kafka-client-serdes.adoc
  docs/modules/ROOT/pages/getting-started/assembly-configuring-the-registry.adoc
  docs/modules/ROOT/pages/getting-started/assembly-installing-registry-docker.adoc
  docs/modules/ROOT/pages/getting-started/assembly-installing-registry-openshift.adoc
  docs/modules/ROOT/pages/getting-started/assembly-installing-registry-storage-openshift.adoc
  docs/modules/ROOT/pages/getting-started/assembly-intro-to-registry-rules.adoc
  docs/modules/ROOT/pages/getting-started/assembly-intro-to-the-registry.adoc
  docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-api.adoc
  docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-maven.adoc
  docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
  docs/modules/ROOT/pages/getting-started/assembly-migrating-registry-v1-v2.adoc
  docs/modules/ROOT/pages/getting-started/assembly-registry-reference.adoc
  docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
  docs/modules/ROOT/pages/getting-started/assembly-using-the-registry-client.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-web-console.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: area/storage, area/rules

#2727 fix: check if ContentCreateRequest has content field
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
Labels: area/rest-api

#2728 Fix reflection configuration for native-image
  app/src/main/java/io/apicurio/registry/ApicurioRegisterForReflection.java
  app/tools/extractRegisterForReflection.java
Labels: area/rules

#2718 feat: better handling of version string unique key violation exception
  app/src/main/java/io/apicurio/registry/services/http/RegistryExceptionMapperService.java
  app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/VersionAlreadyExistsException.java
  app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecorator.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  client/src/main/java/io/apicurio/registry/rest/client/exception/ExceptionMapper.java
  client/src/main/java/io/apicurio/registry/rest/client/exception/VersionAlreadyExistsException.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/ApicurioV2BaseIT.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
Labels: area/storage, area/rest-client

#2738 Implement Change Owner modal in the UI
  ui/config/config-keycloakjs-rbac.js
  ui/config/config-keycloakjs.js
  ui/package.json
  ui/src/app/components/common/ifAuth.tsx
  ui/src/app/pages/artifactVersion/artifactVersion.tsx
  ui/src/app/pages/artifactVersion/components/modals/changeOwnerModal.tsx
  ui/src/app/pages/artifactVersion/components/tabs/info.tsx
  ui/src/app/pages/roles/components/modals/grantAccessModal.tsx
  ui/src/app/pages/roles/components/modals/selectPrincipalAccount.tsx
  ui/src/models/artifactOwner.model.ts
  ui/src/models/index.ts
  ui/src/services/auth/auth.service.ts
  ui/src/services/groups/groups.service.ts
  ui/tsconfig.json
Labels: Impacts Documentation, area/ui
