Repository Apicurio/apicurio-registry, pull requests merged in 2022-12, with the labels that each got.

#3005 Fix images build
  .github/scripts/build-and-push-multiarch-images.sh
  .github/workflows/release-images.yaml
  .github/workflows/verify.yaml
Labels: area/ui

#3004 Update(OperatorGroup): Create OperatorGroup at the beginning of test(s)
  new-system-tests/src/test/java/io/apicurio/registry/systemtests/SqlKeycloak.java
  new-system-tests/src/test/java/io/apicurio/registry/systemtests/SqlNoIAM.java
  new-system-tests/src/test/resources/common/00_operator_group.yaml
Labels: area/storage

#3002 correct mssql statements
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/mssql.ddl
Labels: area/storage

#2992 Generate the rest layer using the quarkus extension
  common/pom.xml
  common/src/main/resources/application.properties
Labels: triage/needs-triage

#3025 Fix docker distro
  Makefile
  distro/docker/pom.xml
Labels: triage/needs-triage

#3029 Revert adding commit id plugin
  app/src/main/assembly/assembly.xml
  distro/docker/src/main/docker/Dockerfile.native
  pom.xml
  storage/kafkasql/src/main/assembly/assembly.xml
  storage/sql/src/main/assembly/assembly.xml
Labels: area/storage

#3030 Remove leftover from tenant limits configuration service
  app/src/main/java/io/apicurio/registry/mt/limits/TenantLimitsConfigurationService.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
Labels: triage/needs-triage

#3031 Remove storage injection from tenant manager client producer
  app/src/main/java/io/apicurio/registry/mt/TenantManagerClientProducer.java
Labels: area/storage

#3032 Fix(workflow): Update minikube versions
  .github/workflows/new-system-tests.yaml
Labels: triage/needs-triage

#3033 Fix NPE in Protobuf compatibility checking
  schema-util/protobuf/src/main/java/io/apicurio/registry/rules/compatibility/protobuf/ProtobufCompatibilityCheckerLibrary.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufFile.java
Labels: area/compatibility, area/rules

#3037 Bring back commit id plugin with a flag to disable it on demand
  .github/workflows/verify.yaml
  pom.xml
Labels: triage/needs-triage

#3040 Use the new retrocompatible client instead of horrific hacks
  integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/KafkaSqlStorageUpgradeIT.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/RetrocompatibleRegistryClientUtils.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/SqlStorageUpgradeIT.java
  pom.xml
Labels: area/storage

#3039 Enable automerge of dependabot semver patches
  .github/workflows/dependabot-automerge.yaml
Labels: triage/needs-triage

#3042 Fix http events sink
  app/src/main/java/io/apicurio/registry/events/http/HttpEventSink.java
  app/src/test/java/io/apicurio/registry/events/HttpEventsProfile.java
  app/src/test/java/io/apicurio/registry/events/HttpEventsTest.java
Labels: triage/needs-triage

#3043 Fix wrong logs in storage metrics store
  app/src/main/java/io/apicurio/registry/storage/metrics/StorageMetricsStore.java
Labels: area/storage

#3047 fix: unset the singleton option for react-router-dom
  ui/webpack.common.js
Labels: area/ui

#3048 Fix dependabot automerge workflow syntax
  .github/workflows/dependabot-automerge.yaml
Labels: triage/needs-triage

#3049 Fix Image release workflow
  .github/workflows/release-images.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  Makefile
Labels: triage/needs-triage

#3053 Use squash to merge dependabot updates
  .github/workflows/dependabot-automerge.yaml
Labels: triage/needs-triage

#3054 Fetch artifact type from artifact metadata in the compatibility api
  app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
Labels: area/compatibility, area/storage

#3056 Dependabot autoapprove
  .github/workflows/dependabot-autoapprove.yaml
Labels: triage/needs-triage

#3058 Ensure the kafka consumer thread starts *after* the SQL db is initialized
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStorageEvent.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStorageEventType.java
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
Labels: area/storage
