Repository Apicurio/apicurio-registry, pull requests merged in 2023-07, with the labels that each got.

#3496 Handle avro complex types in serdes
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  app/src/test/resources/io/apicurio/registry/serde/AvroSchemaB.avsc
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaParser.java
Labels: area/serdes

#3506 docs: add section on HTTP basic client credentials token expiry
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
Labels: Documentation, area/auth

#3514 Add header for group customization in the ccompat api
  app/src/main/java/io/apicurio/registry/ccompat/rest/v6/impl/SubjectsResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/CompatibilityResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/ConfigResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/SchemasResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/SubjectVersionsResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/SubjectsResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CompatibilityResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SchemasResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectVersionsResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectsResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacade.java
  app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
  app/src/test/java/io/apicurio/registry/ccompat/ConfluentSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentClientV7Test.java
Labels: area/compatibility, area/storage

#3515 Fix kafkasql image building
  Makefile
Labels: area/ui, area/storage

#3518 Add scope for basic auth
  app/src/main/resources/application.properties
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  pom.xml
Labels: triage/needs-triage

#3466 Correctly handle non snake-case query parameters in the Python sdk
  python-sdk/Makefile
  python-sdk/kiota-gen.py
  python-sdk/poetry.lock
  python-sdk/pyproject.toml
  python-sdk/tests/basic_test.py
Labels: triage/needs-triage

#3519 Eagerly start and initialize EventsService before EventSourcedRegistryStorage
  app/src/main/java/io/apicurio/registry/events/EventSourcedRegistryStorage.java
  app/src/main/java/io/apicurio/registry/events/EventsService.java
  app/src/main/java/io/apicurio/registry/events/EventsServiceImpl.java
Labels: area/storage

#3531 Update kafka client libraries
  pom.xml
  utils/kafka/pom.xml
Labels: triage/needs-triage

#3537 docs: fix keycloak auth server URL config
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
Labels: Documentation, area/auth

#3538 Updates to support using Azure AD directly for API authn/authz.
  app/src/test/java/io/apicurio/registry/auth/MojoAuthTest.java
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/config/ConfigurationTest.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java
Labels: triage/needs-triage

#3540 v2.4.x ref doc cleanup
  docs/generateAllConfigPartial.java
  docs/local-test-playbook.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/getting-started/assembly-artifact-reference.adoc
  docs/modules/ROOT/pages/getting-started/assembly-config-reference.adoc
  docs/modules/ROOT/pages/getting-started/assembly-configuring-the-registry.adoc
  docs/modules/ROOT/pages/getting-started/assembly-rule-reference.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-rest-api.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-rules.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-web-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-rules-using-console.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.template
  docs/modules/ROOT/partials/getting-started/ref-registry-artifact-metadata.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-rule-precedence.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: area/rules
