Repository Apicurio/apicurio-registry, pull requests merged in 2023-01, with the labels that each got.

#3071 Add dereferencing config to serdes and implement avro flavor
  app/src/test/java/io/apicurio/registry/noprofile/resolver/SchemaResolverTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaParser.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaParser.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaParser.java
  serdes/protobuf-serde/src/main/java/io/apicurio/registry/serde/protobuf/ProtobufSchemaParser.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java
Labels: area/serdes

#3076 Fallback to a fixed list of artifact types
  ui/src/models/artifactTypes.model.ts
Labels: area/ui

#3080 fix: throw exception when an empty schema is provided in the compatib…
  app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
Labels: area/storage

#3089 Handle enum artifact reference and record id strategy
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaParser.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/strategy/RecordIdStrategy.java
Labels: area/serdes

#3087 New(Utils): Functions for work with Deployment and Kafka resources
  new-system-tests/pom.xml
  new-system-tests/src/test/java/io/apicurio/registry/systemtests/Utils.java
Labels: triage/needs-triage

#3090 New(tests): Deploy of Registry with KafkaSQL storage and without IAM
  new-system-tests/src/main/java/io/apicurio/registry/systemtests/Constants.java
  new-system-tests/src/test/java/io/apicurio/registry/systemtests/KafkasqlNoAuthNoIAM.java
  new-system-tests/src/test/resources/apicurio/02_registry_kafkasql_no_auth_no_iam.yaml
  new-system-tests/src/test/resources/kafkasql/01_subscription.yaml
  new-system-tests/src/test/resources/kafkasql/02_no_auth.yaml
Labels: area/storage

#3092 New(tests): Deploy of Registry with KafkaSQL storage and Keycloak IAM
  new-system-tests/src/test/java/io/apicurio/registry/systemtests/KafkasqlNoAuthKeycloak.java
  new-system-tests/src/test/resources/apicurio/02_registry_kafkasql_no_auth_keycloak.yaml
Labels: area/storage

#3093 Update(ui/artifactTypes.model.ts): Add missing XML artifact type
  ui/src/models/artifactTypes.model.ts
Labels: area/ui

#3097 Simplify Java Gen Maven plugin workflow
  new-system-tests/pom.xml
Labels: triage/needs-triage

#3096 SearchedGroup.createdBy should be a String
  app/src/main/java/io/apicurio/registry/storage/dto/SearchedGroupDto.java
  common/src/main/resources/META-INF/openapi.json
Labels: area/storage

#3099 docs: actualise validity rules values for XSD & WSDL
  docs/modules/ROOT/partials/getting-started/ref-registry-rule-maturity-matrix.adoc
Labels: area/rules

#3105 docs: minor clean up from downstream testing
  CONTRIBUTING.md
  docs/modules/ROOT/partials/getting-started/con-registry-serde.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-postgresql-operatorhub.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
  docs/modules/ROOT/partials/getting-started/proc-setting-up-postgresql-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-client.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation, area/storage

#3104 Use vertx http client for internal requests
  app/pom.xml
  app/src/main/java/io/apicurio/registry/faulttolerance/FaultToleranceConstants.java
  app/src/main/java/io/apicurio/registry/mt/TenantContextLoader.java
  app/src/main/java/io/apicurio/registry/mt/TenantManagerClientProducer.java
  app/src/main/java/io/apicurio/registry/mt/TenantReaper.java
  app/src/main/java/io/apicurio/registry/services/auth/CustomAuthenticationMechanism.java
Labels: triage/needs-triage
