Repository Apicurio/apicurio-registry, pull requests merged in 2023-10, with the labels that each got.

#3738 Fix mysql images release
  .github/scripts/build-and-push-multiarch-images.sh
  Makefile
Labels: area/storage

#3782 Enable dependabot for the 2.5.x branch
  .github/dependabot.yml
Labels: triage/needs-triage

#3798 Fixed a regression in the Settings page search box
  ui/src/app/pages/settings/settings.tsx
Labels: area/ui

#3799 Fix typo
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlProtobufCanonicalizerUpgrader.java
Labels: area/storage

#3800 Add null checks on role mapping
  app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
  app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java
Labels: area/rest-api

#3823 feat(schema-cache): ERCache.configureFaultTolerantRefresh #3807
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java
Labels: triage/needs-triage

#3739 Remove sentry integration
  app/pom.xml
  app/src/main/java/io/apicurio/registry/logging/sentry/SentryConfiguration.java
  app/src/main/resources/application.properties
  pom.xml
  ui/src/services/config/config.type.ts
Labels: area/ui

#3646 Change content canonicalizer for AVRO to improve schema evolution and…
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CCompatConfig.java
  app/src/main/java/io/apicurio/registry/rules/RulesService.java
  app/src/main/java/io/apicurio/registry/rules/RulesServiceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/content/ContentCanonicalizerTest.java
  schema-util/avro/pom.xml
  schema-util/avro/src/main/java/io/apicurio/registry/content/canon/EnhancedAvroContentCanonicalizer.java
  schema-util/avro/src/test/java/io/apicurio/registry/content/canon/AvroCompatibilityChecker.java
  schema-util/avro/src/test/java/io/apicurio/registry/content/canon/AvroCompatibilityTest.java
  schema-util/avro/src/test/java/io/apicurio/registry/content/canon/SchemaNormalizerTest.java
  schema-util/avro/src/test/resources/avro/advanced/schema-deeply-nested-enum-default.avsc
  schema-util/avro/src/test/resources/avro/advanced/schema-with-java-type.avsc
  schema-util/avro/src/test/resources/avro/advanced/schema-with-logicaltype.avsc
  schema-util/avro/src/test/resources/avro/advanced/schema-with-null-union.avsc
  schema-util/avro/src/test/resources/avro/simple/schema-self-ref-array-item.avsc
  schema-util/avro/src/test/resources/avro/simple/schema-self-ref-union.avsc
  schema-util/avro/src/test/resources/avro/simple/schema-with-same-nested-schema.avsc
  schema-util/avro/src/test/resources/avro/simple/schema-with-same-nested-schema2.avsc
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AvroArtifactTypeUtilProvider.java
Labels: area/compatibility, area/storage, area/rules

#3836 Upgrade to the latest quarkus
  pom.xml
Labels: 3.x

#3815 docs: add artifact metadata descriptions
  docs/modules/ROOT/pages/getting-started/assembly-installing-registry-openshift.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
  docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-artifact-metadata.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
Labels: Documentation, area/storage

#3818 Add option to skip the register goal
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegisterRegistryMojoTest.java
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoTestBase.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: Impacts Documentation

#3839 fix(schema-resolver): caching of latest artifacts and resilient schema updates
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java
Labels: triage/needs-triage

#3855 Make apicurio-registry work properly with Visual Studio Code
  common/pom.xml
  operator/model/pom.xml
  storage/mssql/pom.xml
  storage/sql/pom.xml
  ui/pom.xml
Labels: area/ui, area/storage

#3826 fix(schema-resolver): caching of latest artifacts #3834
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java
Labels: triage/needs-triage

#3870 Add note on importing the project with IntelliJ
  README.md
Labels: triage/needs-triage

#3875 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: triage/needs-triage

#3887 Improve http events test behaviour
  app/src/test/java/io/apicurio/registry/events/HttpEventsTest.java
Labels: triage/needs-triage

#3834 Add util methods to parse proto files with dependencies
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ProtobufDirectoryParser.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
  utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/broken/helloworld.proto
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/mypackage0/producerId.proto
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/mypackage2/version.proto
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/producer.proto
Labels: triage/needs-triage

#3863 #3862 adds ReflectAllowNullAvroDatumProvider
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaUtils.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/ReflectAllowNullAvroDatumProvider.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/ReflectAvroDatumProvider.java
Labels: area/serdes

#3898 Fix protobuf canonicalizer upgrader
  .github/workflows/integration-tests.yaml
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlProtobufCanonicalizerUpgrader.java
Labels: area/storage

#3892 Bump Kiota Maven plugin
  app/src/test/java/io/apicurio/registry/AbstractRegistryTestBase.java
  app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
  app/src/test/java/io/apicurio/registry/auth/AuthTestAnonymousCredentials.java
  app/src/test/java/io/apicurio/registry/limits/LimitsTest.java
  app/src/test/java/io/apicurio/registry/noprofile/compatibility/CompatibilityRuleApplicationTest.java
  app/src/test/java/io/apicurio/registry/rbac/AdminClientTest.java
  app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java
  client/pom.xml
  integration-tests/src/test/java/io/apicurio/tests/ApicurioRegistryBaseIT.java
  integration-tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java
Labels: area/compatibility, area/rest-client

#3903 docs: bump docs versions for v2.5 release
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation

#3904 docs: clean up link attributes and versions
  docs/modules/ROOT/partials/shared/attributes-links.adoc
Labels: Documentation
