Repository Apicurio/apicurio-registry, pull requests merged in 2023-08, with the labels that each got.

#3548 Address snakeyaml critical cve
  app/pom.xml
  pom.xml
Labels: triage/needs-triage

#3550 Remove unused dependency
  .github/dependabot.yml
  pom.xml
Labels: triage/needs-triage

#3565 Revert "build(deps): bump tough-cookie and ts-jest in /ui"
  ui/package-lock.json
  ui/package.json
Labels: area/ui

#3571 Add the ability to skip the python sdk release
  .github/workflows/release.yaml
Labels: triage/needs-triage

#3572 Finish the ability to skip the python sdk release
  .github/workflows/release.yaml
Labels: triage/needs-triage

#3573 Added a milestone release workflow
  .github/workflows/milestone-release.yaml
Labels: triage/needs-triage

#3574 Enable dependabot for Python
  .github/dependabot.yml
Labels: triage/needs-triage

#3587 Bump operator libraries/dependencies
  .github/workflows/operator.yaml
  operator/controller/Readme.md
  operator/controller/pom.xml
  operator/controller/src/main/java/io/apicurio/registry/operator/DeploymentController.java
  operator/controller/src/main/java/io/apicurio/registry/operator/StatusUpdater.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/DeploymentITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/StatusUpdaterTest.java
  operator/model/pom.xml
  operator/pom.xml
Labels: triage/needs-triage

#3600 Remove the IBM compatibility API
  app/etc/openapi.yaml
  app/src/main/java/io/apicurio/registry/ibmcompat/api/Api.java
  app/src/main/java/io/apicurio/registry/ibmcompat/api/ApiService.java
  app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
  app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiUtil.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/EnabledModification.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/NewSchema.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/NewSchemaVersion.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/Schema.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaInfo.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaListItem.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaModificationPatch.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaState.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaSummary.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaVersion.java
  app/src/main/java/io/apicurio/registry/ibmcompat/model/StateModification.java
  app/src/main/java/io/apicurio/registry/ui/servlets/SpecUrlFilter.java
  app/src/main/resources-unfiltered/META-INF/resources/apidocs/index.html
  app/src/main/resources-unfiltered/META-INF/web.xml
  app/src/main/resources/application.properties
  app/src/test/java/io/apicurio/registry/ibmcompat/IBMClientTest.java
  app/src/test/java/io/apicurio/registry/ibmcompat/IBMCompatApiTest.java
  app/src/test/java/io/apicurio/registry/ibmcompat/IBMTestProfile.java
  app/src/test/java/io/apicurio/registry/ibmcompat/SchemaRegistryRestAPIClient.java
  app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTest.java
  app/src/test/java/io/apicurio/registry/rest/DisableApisFlagsTest.java
  app/src/test/java/io/apicurio/registry/rest/DisableApisTestProfile.java
  app/src/test/java/io/apicurio/registry/rest/MultipleRequestFiltersTestProfile.java
  app/src/test/java/io/apicurio/registry/rest/MultitenancyAndDisabledApisTest.java
Labels: area/compatibility

#3605 Fix publishing of the Python SDK
  python-sdk/Makefile
Labels: triage/needs-triage

#3593 Fix Owner Validation
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
Labels: area/rest-api
