Repository Apicurio/apicurio-registry, pull requests merged in 2023-02, with the labels that each got.

#3108 Restore the docs version in antora.yml to something other than main
  .github/workflows/release.yaml
Labels: triage/needs-triage

#3123 chore: remove duplicate tags in openapi-gen
  .github/workflows/update-openapi.yaml
  utils/tools/src/main/java/io/apicurio/registry/utils/tools/TransformOpenApiForClientGen.java
Labels: triage/needs-triage

#3133 Upgrade quarkus and fix broken OpenApi transformer
  pom.xml
  utils/tools/src/main/java/io/apicurio/registry/utils/tools/TransformOpenApiForClientGen.java
Labels: triage/needs-triage

#3128 Add option to minify avro with maven plugin
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithMinifyTest.java
  app/src/test/resources/io/apicurio/registry/noprofile/maven/avro.avsc
  utils/maven-plugin/pom.xml
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterArtifact.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: component/registry

#3136 Fix a typo in index.html
  app/src/main/resources-unfiltered/META-INF/resources/apidocs/index.html
Labels: area/compatibility

#3137 Revert "build(deps): bump confluent.version from 7.3.0 to 7.3.1"
  pom.xml
Labels: area/ui

#3153 Onboarding to Stonesoup
  Dockerfile.jvm.staged
  devfile.yaml
Labels: triage/needs-triage

#3156 Fix stonesoup dockerfile
  Dockerfile.jvm.staged
Labels: triage/needs-triage

#3157 Add profiles to dockerfile
  Dockerfile.jvm.staged
Labels: triage/needs-triage

#3167 fix: prevent JSON schema library from attempting to retrieve referenced schemas. Fixes #3086
  app/src/test/java/io/apicurio/registry/noprofile/rest/v1/ArtifactsResourceTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v1/TestResourceTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
  schema-util/common/src/main/java/io/apicurio/registry/rules/RuleViolationException.java
  schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonUtil.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/JsonSchemaContentValidatorTest.java
Labels: area/compatibility, area/rules
