Repository Apicurio/apicurio-registry, pull requests merged in 2023-05, with the labels that each got.

#3273 Use multitenant common component
  app/pom.xml
  app/src/main/java/io/apicurio/registry/auth/AdminOverride.java
  app/src/main/java/io/apicurio/registry/auth/AuthorizedInterceptor.java
  app/src/main/java/io/apicurio/registry/config/RegistryStorageConfigCache.java
  app/src/main/java/io/apicurio/registry/faulttolerance/FaultToleranceConstants.java
  app/src/main/java/io/apicurio/registry/metrics/RestMetricsResponseFilter.java
  app/src/main/java/io/apicurio/registry/metrics/StorageMetricsInterceptor.java
  app/src/main/java/io/apicurio/registry/mt/MultitenancyProperties.java
  app/src/main/java/io/apicurio/registry/mt/RegistryTenantContext.java
  app/src/main/java/io/apicurio/registry/mt/TenantContext.java
  app/src/main/java/io/apicurio/registry/mt/TenantContextImpl.java
  app/src/main/java/io/apicurio/registry/mt/TenantContextLoader.java
  app/src/main/java/io/apicurio/registry/mt/TenantForbiddenException.java
  app/src/main/java/io/apicurio/registry/mt/TenantIdResolver.java
  app/src/main/java/io/apicurio/registry/mt/TenantManagerClientProducer.java
  app/src/main/java/io/apicurio/registry/mt/TenantMetadataService.java
  app/src/main/java/io/apicurio/registry/mt/TenantNotAuthorizedException.java
  app/src/main/java/io/apicurio/registry/mt/TenantNotFoundException.java
  app/src/main/java/io/apicurio/registry/mt/TenantReaper.java
  app/src/main/java/io/apicurio/registry/mt/limits/RegistryStorageLimitsEnforcer.java
  app/src/main/java/io/apicurio/registry/mt/limits/RegistryTenantLimitsConfiguration.java
  app/src/main/java/io/apicurio/registry/mt/limits/RegistryTenantLimitsConfigurationService.java
  app/src/main/java/io/apicurio/registry/mt/limits/RegistryTenantLimitsService.java
  app/src/main/java/io/apicurio/registry/mt/logging/MdcContextProvider.java
  app/src/main/java/io/apicurio/registry/rest/RegistryApplicationServletFilter.java
  app/src/main/java/io/apicurio/registry/rest/v2/SystemResourceImpl.java
  app/src/main/java/io/apicurio/registry/services/DisabledApisMatcherService.java
  app/src/main/java/io/apicurio/registry/services/http/RegistryExceptionMapperService.java
  app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/metrics/StorageMetricsStore.java
  app/src/main/resources/META-INF/services/org.eclipse.microprofile.context.spi.ThreadContextProvider
  app/src/main/resources/application-dev.properties
  app/src/main/resources/application-prod.properties
  app/src/main/resources/application-test.properties
  app/src/main/resources/application.properties
  app/src/test/java/io/apicurio/registry/mt/MockTenantMetadataService.java
  app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTest.java
  app/src/test/java/io/apicurio/registry/noprofile/storage/AbstractRegistryStorageTest.java
  client/src/main/java/io/apicurio/registry/rest/client/impl/ErrorHandler.java
  common/src/main/java/io/apicurio/registry/rest/Headers.java
  docs/generateAllConfigPartial.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  pom.xml
  storage/kafkasql/pom.xml
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlSink.java
  storage/kafkasql/src/test/resources/test-overlay.properties
  storage/mssql/pom.xml
  storage/mssql/src/main/resources/overlay.properties
  storage/mssql/src/test/resources/test-overlay.properties
  storage/pom.xml
  storage/sql/pom.xml
  storage/sql/src/test/resources/test-overlay.properties
Labels: area/rest-api, area/storage, area/rest-client

#3299 Add delay downloads reaper
  app/src/main/java/io/apicurio/registry/downloads/DownloadReaper.java
Labels: triage/needs-triage

#3300 Fix kafka upgrader
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlUpgrader.java
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlStore.java
Labels: area/storage

#3312 Fix dynamic config property resolve
  app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
Labels: area/rest-api

#3311 Upgrade compile jdk to 17
  .github/workflows/integration-tests.yaml
  .github/workflows/kubernetes-tests-manual.yaml
  .github/workflows/kubernetes-tests.yaml
  .github/workflows/maven-snapshot-release.yaml
  .github/workflows/new-system-tests.yaml
  .github/workflows/publish-debug-image.yaml
  .github/workflows/registry-rhbq-build.yaml
  .github/workflows/release-images.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-registry-examples.yaml
  .github/workflows/tool-exportV1-release.yaml
  .github/workflows/update-openapi.yaml
  .github/workflows/verify.yaml
  distro/docker/src/main/docker/Dockerfile.jvm
  distro/docker/src/main/docker/Dockerfile.kafkasql.jvm
  distro/docker/src/main/docker/Dockerfile.mssql.jvm
  distro/docker/src/main/docker/Dockerfile.sql.jvm
  integration-tests/integration-tests-common/pom.xml
  integration-tests/legacy-tests/pom.xml
  new-system-tests/pom.xml
  pom.xml
  system-tests/pom.xml
Labels: area/storage

#3320 Added UI support for viewing artifact references
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v2/IdsResourceImpl.java
  app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecorator.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ArtifactReferenceDtoMapper.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
  common/src/main/resources/META-INF/openapi.json
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
  ui/package-lock.json
  ui/package.json
  ui/src/app/components/common/ListWithToolbar.tsx
  ui/src/app/components/common/index.ts
  ui/src/app/pages/artifactVersion/artifactVersion.tsx
  ui/src/app/pages/artifactVersion/components/tabs/refList.tsx
  ui/src/app/pages/artifactVersion/components/tabs/references.css
  ui/src/app/pages/artifactVersion/components/tabs/references.tsx
  ui/src/app/pages/artifactVersion/components/tabs/refsToolbar.css
  ui/src/app/pages/artifactVersion/components/tabs/refsToolbar.tsx
  ui/src/models/artifactReference.model.ts
  ui/src/models/referenceType.ts
  ui/src/services/groups/groups.service.ts
Labels: area/ui, area/rest-api, area/storage

#3332 Implemented most of the UX design for Client SDK Gen
  app/src/main/java/io/apicurio/registry/ui/config/UiConfigProperties.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  ui/config/config-keycloakjs-rbac.js
  ui/config/config-keycloakjs.js
  ui/config/config-none.js
  ui/config/config-oidcjs.js
  ui/package-lock.json
  ui/package.json
  ui/src/app/pages/artifactVersion/components/modals/generateClientModal.css
  ui/src/app/pages/artifactVersion/components/modals/generateClientModal.tsx
  ui/src/app/pages/artifactVersion/components/tabs/info.css
  ui/src/app/pages/artifactVersion/components/tabs/info.tsx
  ui/src/services/config/config.service.ts
  ui/src/services/downloader/downloader.service.ts
  ui/webpack.common.js
Labels: area/ui

#3334 Update webpack.common.js with new URL
  ui/webpack.common.js
Labels: area/ui

#3319 Kiota based Python sdk
  .github/workflows/python-sdk.yaml
  .github/workflows/release.yaml
  python-sdk/.gitignore
  python-sdk/Makefile
  python-sdk/README.md
  python-sdk/kiota-gen.py
  python-sdk/poetry.lock
  python-sdk/pyproject.toml
  python-sdk/python_sdk/__init__.py
  python-sdk/tests/basic_test.py
Labels: triage/needs-triage

#3352 Updates for the Python SDK release
  .github/workflows/release.yaml
  python-sdk/pyproject.toml
Labels: triage/needs-triage

#3361 rename the root folder of the Python SDK
  .github/workflows/python-sdk.yaml
  .gitignore
  python-sdk/.gitignore
  python-sdk/apicurioregistrysdk/__init__.py
  python-sdk/kiota-gen.py
  python-sdk/pyproject.toml
  python-sdk/tests/basic_test.py
Labels: triage/needs-triage

#3351 Maven directory resolver
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithAutoReferencesTest.java
  app/src/test/resources/io/apicurio/registry/noprofile/maven/TradeRawArray.avsc
  app/src/test/resources/io/apicurio/registry/noprofile/maven/citizen.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/citizenIdentifier.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/city.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/mode.proto
  app/src/test/resources/io/apicurio/registry/noprofile/maven/qualification.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/table_info.proto
  app/src/test/resources/io/apicurio/registry/noprofile/maven/table_notification.proto
  app/src/test/resources/io/apicurio/registry/noprofile/maven/table_notification_type.proto
  schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonUtil.java
  utils/maven-plugin/pom.xml
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractDirectoryParser.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AvroDirectoryParser.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/JsonSchemaDirectoryParser.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ParsedDirectoryWrapper.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ProtobufDirectoryParser.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterArtifact.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
Labels: area/compatibility, area/rules

#3382 Override the version of mime4j used by the KC admin client
  utils/tests/pom.xml
Labels: triage/needs-triage

#3384 Release storage variants to maven repo
  .github/workflows/release.yaml
Labels: area/storage

#3386 Support reading headers in converters
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/SerdeBasedConverter.java
Labels: triage/needs-triage

#3377 Minor adjustments for the Python SDK
  python-sdk/Makefile
  python-sdk/kiota-gen.py
Labels: triage/needs-triage

#3383 Implemented the all-refs-must-be-mapped part of the new integrity rule
  app/src/main/java/io/apicurio/registry/rules/integrity/IntegrityRuleExecutor.java
  pom.xml
  schema-util/avro/src/main/java/io/apicurio/registry/rules/validity/AvroContentValidator.java
  schema-util/common/src/main/java/io/apicurio/registry/rules/validity/ContentValidator.java
  schema-util/graphql/src/main/java/io/apicurio/registry/rules/validity/GraphQLContentValidator.java
  schema-util/json/src/main/java/io/apicurio/registry/rules/validity/JsonSchemaContentValidator.java
  schema-util/kconnect/src/main/java/io/apicurio/registry/rules/validity/KafkaConnectContentValidator.java
  schema-util/openapi/src/main/java/io/apicurio/registry/rules/validity/ApicurioDataModelContentValidator.java
  schema-util/protobuf/src/main/java/io/apicurio/registry/rules/validity/ProtobufContentValidator.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/AvroContentValidatorTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/OpenApiContentValidatorTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/ProtobufContentValidatorTest.java
  schema-util/util-provider/src/test/resources/io/apicurio/registry/rules/validity/avro-valid-with-refs.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/rules/validity/openapi-valid-with-refs.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/rules/validity/protobuf-valid-with-refs.proto
  schema-util/xml/src/main/java/io/apicurio/registry/rules/validity/XmlContentValidator.java
Labels: area/rules

#3391 Upgraded to the latest asyncapi UI
  ui/package-lock.json
  ui/package.json
Labels: area/ui

#3392 Upgrade to data-models 2.0.3
  pom.xml
Labels: triage/needs-triage

#3394 fix: use right filepath
  .github/workflows/release.yaml
Labels: triage/needs-triage

#3396 Fix Python SDK release path
  .github/workflows/release.yaml
Labels: triage/needs-triage

#3398 docs: add artifact ref integrity rule, clean up
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-rules.png
  docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-overview.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-rules.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-rules-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-rule-maturity-matrix.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-rule-precedence.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-rule-types.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation, area/storage, area/rules
