Repository Apicurio/apicurio-registry, pull requests merged in 2023-11, with the labels that each got.

#3909 docs: clean up v2.4.x versions
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation

#3906 docs: bump docs versions in main for v3.0
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation

#3912 Remove obsolete IntelliJ remark
  README.md
Labels: triage/needs-triage

#3933 Added a new About modal in the UI
  ui/.scripts/generate-version.cjs
  ui/ui-app/config/version.js
  ui/ui-app/public/apicurio_registry_icon_reverse.svg
  ui/ui-app/src/app/components/auth/IfAuth.tsx
  ui/ui-app/src/app/components/auth/index.ts
  ui/ui-app/src/app/components/common/index.ts
  ui/ui-app/src/app/components/header/AppAboutModal.tsx
  ui/ui-app/src/app/components/header/AppHeader.css
  ui/ui-app/src/app/components/header/AppHeader.tsx
  ui/ui-app/src/app/components/header/AppHeaderToolbar.tsx
  ui/ui-app/src/app/components/header/AvatarDropdown.css
  ui/ui-app/src/app/components/header/AvatarDropdown.tsx
  ui/ui-app/src/app/components/header/index.ts
  ui/ui-app/src/services/index.ts
  ui/ui-app/src/services/services.ts
  ui/ui-app/src/services/version/index.ts
  ui/ui-app/src/services/version/version.service.ts
  ui/ui-app/src/services/version/version.type.ts
Labels: area/ui

#3940 Restore the Documentation tab for OpenAPI artifacts
  ui/.docker-scripts/create-config.cjs
  ui/.docker-scripts/nginx.conf
  ui/README.md
  ui/tests/package.json
  ui/ui-app/README.md
  ui/ui-app/configs/config-3scale.js
  ui/ui-app/configs/config-none.js
  ui/ui-app/configs/config-oidc-rbac.js
  ui/ui-app/configs/config-oidc.js
  ui/ui-app/configs/version.js
  ui/ui-app/init-dev.sh
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/src/app/pages/artifactVersion/ArtifactVersionPage.css
  ui/ui-app/src/app/pages/artifactVersion/ArtifactVersionPage.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/DocumentationTabContent.css
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/DocumentationTabContent.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/visualizers/AsyncApiVisualizer.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/visualizers/OpenApiVisualizer.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/visualizers/index.ts
  ui/ui-app/src/services/auth/auth.service.ts
  ui/ui-app/src/services/config/config.service.ts
  ui/ui-app/src/services/config/config.type.ts
  ui/ui-docs/.eslintrc.cjs
  ui/ui-docs/index.html
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
  ui/ui-docs/src/app/App.tsx
  ui/ui-docs/src/app/DemoData.ts
  ui/ui-docs/src/app/components/common/If.tsx
  ui/ui-docs/src/app/hooks/useWindow.ts
  ui/ui-docs/vite.config.ts
Labels: area/ui

#3941 Added UI tests for global rules and settings pages
  ui/tests/playwright.config.ts
  ui/tests/specs/globalRules.spec.ts
  ui/tests/specs/settings.spec.ts
  ui/tests/tests-examples/demo-todo-app.spec.ts
  ui/tests/tests-examples/example.spec.ts
  ui/ui-app/src/app/components/common/ObjectDropdown.tsx
  ui/ui-app/src/app/components/common/ObjectSelect.tsx
  ui/ui-app/src/app/components/header/AppAboutModal.tsx
  ui/ui-app/src/app/components/ruleList/CompatibilityDropdown.tsx
  ui/ui-app/src/app/components/ruleList/CompatibilitySelect.tsx
  ui/ui-app/src/app/components/ruleList/IntegritySelect.tsx
  ui/ui-app/src/app/components/ruleList/RuleList.tsx
  ui/ui-app/src/app/components/ruleList/ValidityDropdown.tsx
  ui/ui-app/src/app/components/ruleList/ValiditySelect.tsx
  ui/ui-app/src/app/components/ruleList/index.ts
  ui/ui-app/src/app/pages/artifacts/components/toolbar/ArtifactsPageToolbar.tsx
  ui/ui-app/src/app/pages/artifacts/components/uploadForm/UploadArtifactForm.tsx
  ui/ui-app/src/app/pages/settings/SettingsPage.tsx
Labels: area/ui, area/compatibility, area/rules

#3942 Experiment: use Groups for dependabot dependencies
  .github/dependabot.yml
Labels: triage/needs-triage

#3950 Added an e2e test to the playwright ui tests
  ui/tests/specs/data/openapi-simple-invalid.ts
  ui/tests/specs/data/openapi-simple-v2.ts
  ui/tests/specs/data/openapi-simple.ts
  ui/tests/specs/e2e.spec.ts
  ui/tests/specs/globalRules.spec.ts
  ui/ui-app/src/app/components/common/UrlUpload.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/modals/EditMetaDataModal.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/modals/PropertiesFormGroup.tsx
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/InfoTabContent.tsx
  ui/ui-app/src/app/pages/artifacts/ArtifactsPage.tsx
  ui/ui-app/src/app/pages/artifacts/components/toolbar/ArtifactsPageToolbar.tsx
  ui/ui-app/src/app/pages/artifacts/components/uploadForm/UploadArtifactForm.tsx
Labels: area/ui, area/rules

#3955 added a quarkus json logging for the registry app
  app/pom.xml
  app/src/main/resources/application.properties
Labels: triage/needs-triage

#3957 Fix incorrect .orElse usage.
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
Labels: triage/needs-triage

#3960 Simplify login workflow
  ui/ui-app/src/services/auth/auth.service.ts
Labels: area/ui

#3963 Custom authentication exception mapper
  app/src/main/java/io/apicurio/registry/rest/AuthenticationFailedExceptionMapper.java
  app/src/main/java/io/apicurio/registry/rest/RegistryExceptionMapper.java
  app/src/main/java/io/apicurio/registry/services/http/RegistryExceptionMapperService.java
  app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
  storage/mysql/pom.xml
Labels: area/rest-api, area/storage

#3965 Add util methods to parse proto files with dependencies
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ProtobufDirectoryParser.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
  utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/broken/helloworld.proto
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/mypackage0/producerId.proto
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/mypackage2/version.proto
  utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/producer.proto
Labels: triage/needs-triage

#3964 Improve http events test behaviour
  app/src/test/java/io/apicurio/registry/events/HttpEventsTest.java
Labels: triage/needs-triage

#3966 Backport fixes
  app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/storage/ArtifactStateExt.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
  app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  ui/src/app/pages/settings/settings.tsx
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ConnectEnum.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ConnectUnion.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
  utils/converter/src/test/java/io/apicurio/registry/utils/converter/avro/AvroDataTest.java
Labels: area/ui, area/rest-api, area/storage

#3968 Fix mysql build
  storage/mysql/pom.xml
Labels: area/ui, area/storage

#3979 Update dependabot
  .github/dependabot.yml
  app/pom.xml
  pom.xml
Labels: triage/needs-triage

#4002 Remove unused test dependency
  pom.xml
  utils/tests/pom.xml
Labels: triage/needs-triage

#4019 fix: some health checks are always UP even when a counter hits limit #4018
  app/src/main/java/io/apicurio/registry/metrics/health/liveness/PersistenceExceptionLivenessCheck.java
  app/src/main/java/io/apicurio/registry/metrics/health/liveness/ResponseErrorLivenessCheck.java
  app/src/main/java/io/apicurio/registry/metrics/health/readiness/PersistenceTimeoutReadinessCheck.java
  app/src/main/java/io/apicurio/registry/metrics/health/readiness/ResponseTimeoutReadinessCheck.java
Labels: area/storage

#4026 Remove old instruction
  .github/workflows/verify.yaml
Labels: triage/needs-triage

#4027 Update quarkus to 3.5.3
  pom.xml
Labels: triage/needs-triage

#4030 Add dockerhub login for native image
  .github/workflows/verify.yaml
Labels: triage/needs-triage

#4037 docs: bump rest api and build versions
  docs/modules/ROOT/assets/attachments/registry-rest-api.htm
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation, area/rest-api

#4045 Fix dateformat configuration
  app/src/main/resources/application.properties
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/LegacyDateFormatTest.java
  app/src/test/java/io/apicurio/registry/rest/CustomizeDateFormatTest.java
  app/src/test/java/io/apicurio/registry/rest/CustomizeDateFormatTestProfile.java
  common/pom.xml
Labels: triage/needs-triage

#4071 Fix integration tests h2 image name
  .github/workflows/integration-tests.yaml
Labels: triage/needs-triage

#4070 docs: update rest api location and build version
  docs/modules/ROOT/assets/attachments/registry-rest-api.htm
  docs/modules/ROOT/assets/images/images/getting-started/registry-connect-architecture.png
  docs/modules/ROOT/assets/images/images/getting-started/registry-serdes-architecture.png
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-artifact.png
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-client-sdk.png
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-rules.png
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console.png
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation, area/ui, area/rest-api

#4042 Added Andrea to maintainers list +1
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
  pom.xml
Labels: area/storage

#4072 Fix default integration test images
  integration-tests/pom.xml
Labels: triage/needs-triage
