Repository Apicurio/apicurio-registry, pull requests merged in 2023-12, with the labels that each got.

#4078 docs: add new auto artifact refs implementation in 2.5.x as tech preview feature
  docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-generating-client-sdk-using-web-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
Labels: Documentation

#4105 Add strimzi oauth dependency back
  storage/kafkasql/pom.xml
Labels: area/storage

#4095 add missing ccompat properties
  app/src/main/resources/application.properties
Labels: triage/needs-triage

#4106 Upgrade patternfly
  ui/ui-app/package-lock.json
  ui/ui-app/src/app/components/header/AppHeader.tsx
  ui/ui-app/src/services/config/config.type.ts
  ui/ui-app/vite.config.ts
  ui/ui-docs/vite.config.ts
Labels: area/ui

#4079 Updated the integration testing docs
  TESTING.md
  integration-tests/README.md
Labels: triage/needs-triage

#4127 Add support for autoregister schemas in the json serde
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaParser.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializer.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializerConfig.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaParser.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java
Labels: area/serdes, port-3.x

#4129 Upgrade deps and remove one banned in Quarkus
  pom.xml
  serdes/jsonschema-serde/pom.xml
Labels: area/serdes

#4144 Handle situations with complex schemas in json converter
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java
Labels: triage/needs-triage

#4151 Handle situations with complex schemas in json converter (#4144)
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java
Labels: area/serdes

#4150 Add support for autoregister schemas in the json serde (#4127)
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaParser.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializer.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializerConfig.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaParser.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java
Labels: area/serdes
