Repository Apicurio/apicurio-registry, pull requests merged in 2023-06, with the labels that each got.

#3404 docs: generating client sdk for openapi artifacts
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-client-sdk.png
  docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
  docs/modules/ROOT/partials/getting-started/proc-generating-client-sdk-using-web-console.adoc
Labels: Documentation, triage/needs-triage

#3412 docs: v2.4 UI updates for view-only artifact refs, delete artifact version setting
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-artifact.png
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-settings-using-console.adoc
  docs/modules/ROOT/partials/getting-started/proc-generating-client-sdk-using-web-console.adoc
Labels: Documentation, area/ui

#3423 Add content hash and canonical hash upgrader
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/upgrader/ReferencesCanonicalHashUpgrader.java
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/db-version
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/mssql.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/14/h2.upgrade.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/14/mssql.upgrade.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/14/postgresql.upgrade.ddl
  integration-tests/testsuite/src/main/java/io/apicurio/tests/utils/CustomTestsUtils.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/KafkaSqlStorageUpgradeIT.java
  integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/SqlStorageUpgradeIT.java
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlProtobufCanonicalizerUpgrader.java
  storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlUpgrader.java
Labels: area/storage

#3425 Fix common sql statements
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
Labels: area/storage

#3426 Update compose to use ports instead of host
  distro/docker-compose/README.md
  distro/docker-compose/src/main/resources/docker-compose.apicurio.yml
Labels: triage/needs-triage

#3439 Proposed change to the Maven Plugin: Auto References
  schema-util/asyncapi/src/main/java/io/apicurio/registry/content/refs/AsyncApiReferenceFinder.java
  schema-util/avro/src/main/java/io/apicurio/registry/content/refs/AvroReferenceFinder.java
  schema-util/common/src/main/java/io/apicurio/registry/content/refs/ExternalReference.java
  schema-util/common/src/main/java/io/apicurio/registry/content/refs/JsonPointerExternalReference.java
  schema-util/common/src/main/java/io/apicurio/registry/content/refs/NoOpReferenceFinder.java
  schema-util/common/src/main/java/io/apicurio/registry/content/refs/ReferenceFinder.java
  schema-util/json/src/main/java/io/apicurio/registry/content/refs/JsonSchemaReferenceFinder.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/refs/AbstractDataModelsReferenceFinder.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/refs/OpenApiReferenceFinder.java
  schema-util/protobuf/src/main/java/io/apicurio/registry/content/refs/ProtobufReferenceFinder.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/ArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AsyncApiArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AvroArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/GraphQLArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/JsonArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/KConnectArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/OpenApiArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/ProtobufArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/WsdlArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/XmlArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/XsdArtifactTypeUtilProvider.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/refs/AsyncApiReferenceFinderTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/refs/AvroReferenceFinderTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/refs/JsonSchemaReferenceFinderTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/refs/OpenApiReferenceFinderTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/refs/ProtobufReferenceFinderTest.java
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/refs/asyncapi-with-refs.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/refs/avro-with-refs.avsc
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/refs/json-schema-with-refs.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/refs/openapi-with-refs.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/refs/protobuf-with-refs.proto
  utils/maven-plugin/pom.xml
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ExistingReference.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterArtifact.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/refs/IndexedResource.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/refs/ReferenceIndex.java
Labels: triage/needs-triage

#3458 Fix dynamic basic auth ui resolution
  app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
Labels: area/ui, area/rest-api

#3452 Remove data-models version override from common
  common/pom.xml
Labels: triage/needs-triage

#3459 Native image fully statically linked
  .github/workflows/release-images.yaml
  Makefile
  distro/docker/src/main/docker/Dockerfile.native-scratch
Labels: triage/needs-triage

#3464 Fix RHTAP repo
  .tekton/apicurio-registry-f36x-pull-request.yaml
  .tekton/apicurio-registry-f36x-push.yaml
Labels: triage/needs-triage

#3477 feat: Expose listArtifactTypes in the client library
  app/src/test/java/io/apicurio/registry/rbac/AdminClientTest.java
  client/src/main/java/io/apicurio/registry/rest/client/AdminClient.java
  client/src/main/java/io/apicurio/registry/rest/client/impl/AdminClientImpl.java
  client/src/main/java/io/apicurio/registry/rest/client/request/provider/AdminRequestsProvider.java
  client/src/main/java/io/apicurio/registry/rest/client/request/provider/Routes.java
Labels: area/rest-client
