Repository Apicurio/apicurio-registry, pull requests merged in 2023-09, with the labels that each got.

#3624 Upgraded UI components via npm
  ui/package-lock.json
  ui/package.json
Labels: area/ui

#3614 Implement dereferencing for apicurio-data-models types
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
  app/src/test/resources/io/apicurio/registry/noprofile/rest/v2/openapi-with-external-ref.json
  app/src/test/resources/io/apicurio/registry/noprofile/rest/v2/referenced-types.json
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/ApicurioDataModelsContentDereferencer.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/RegistryReferenceResolver.java
Labels: triage/needs-triage

#3633 Incorrect default value avro serialization
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ConnectEnum.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ConnectUnion.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
  utils/converter/src/test/java/io/apicurio/registry/utils/converter/avro/AvroDataTest.java
Labels: triage/needs-triage

#3653 docs: Clarify AUTH_ENABLED required for auth/authz
  docs/modules/ROOT/pages/getting-started/assembly-configuring-kafka-client-serdes.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-producer.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
  docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation, area/ui

#3639 fix: free disk space on runner to fix out of space issue
  .github/workflows/release-images.yaml
Labels: triage/needs-triage

#3661 feat: GitOps storage variant POC
  .github/workflows/verify.yaml
  Makefile
  app/src/main/java/io/apicurio/registry/storage/decorator/ReadOnlyRegistryStorageDecorator.java
  distro/docker/pom.xml
  distro/docker/src/main/docker/Dockerfile.gitops.jvm
  pom.xml
  storage/gitops/pom.xml
  storage/gitops/src/main/assembly/assembly.xml
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/AbstractReadOnlyRegistryStorage.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/GitManager.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsConfigProperties.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorageProvider.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/ProcessingState.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/YAMLObjectMapper.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/Any.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/GitFile.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/Type.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Artifact.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Content.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Group.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/HasSchema.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Registry.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Rule.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Setting.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/model/v0/Version.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/sql/BlueHandleFactory.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/sql/BlueSqlStorage.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/sql/GreenHandleFactory.java
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/sql/GreenSqlStorage.java
  storage/gitops/src/main/resources-unfiltered/META-INF/resources/api-specifications/gitops/v0/openapi.json
  storage/gitops/src/main/resources/overlay.properties
  storage/gitops/src/test/java/io/apicurio/registry/storage/impl/gitops/GitOpsSmokeTest.java
  storage/gitops/src/test/java/io/apicurio/registry/storage/impl/gitops/GitTestRepository.java
  storage/gitops/src/test/java/io/apicurio/registry/storage/impl/gitops/GitTestRepositoryManager.java
  storage/gitops/src/test/resources/git/empty/registry-test.yaml
  storage/gitops/src/test/resources/git/smoke01/content/.igore-me-3
  storage/gitops/src/test/resources/git/smoke01/content/petstore-1.0.0.yaml
  storage/gitops/src/test/resources/git/smoke01/igore-me-1.yaml
  storage/gitops/src/test/resources/git/smoke01/registry-other.yaml
  storage/gitops/src/test/resources/git/smoke01/registry-test.yaml
  storage/gitops/src/test/resources/git/smoke01/test/artifact-petstore.yaml
  storage/gitops/src/test/resources/git/smoke01/test/content-1.yaml
  storage/gitops/src/test/resources/git/smoke01/test/group-foo.yaml
  storage/gitops/src/test/resources/git/smoke01/test/igore-me-2.yaml
  storage/gitops/src/test/resources/git/smoke02/content/Person.json
  storage/gitops/src/test/resources/git/smoke02/registry-test.yaml
  storage/gitops/src/test/resources/git/smoke02/test/artifact-person.yaml
  storage/gitops/src/test/resources/git/smoke02/test/content-42.yaml
  storage/gitops/src/test/resources/git/smoke02/test/group-bar.yaml
  storage/gitops/src/test/resources/test-overlay.properties
Labels: area/storage

#3666 fix: merge issue
  storage/gitops/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
Labels: area/storage

#3672 Remove black magic for building storages classpath
  pom.xml
  storage/gitops/pom.xml
  storage/kafkasql/pom.xml
  storage/mssql/pom.xml
  storage/sql/pom.xml
Labels: area/ui, area/storage

#3637 Allow idempotent change to artifact state
  app/src/main/java/io/apicurio/registry/storage/ArtifactStateExt.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
Labels: area/rest-api

#3716 feature: MySQL Storage Driver
  Makefile
  README.md
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/MySQLSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatementsProducer.java
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/mysql.ddl
  pom.xml
  storage/mysql/pom.xml
  storage/mysql/src/main/assembly/assembly.xml
  storage/mysql/src/main/java/io/apicurio/registry/storage/impl/sql/MySqlRegistryStorage.java
  storage/mysql/src/main/java/io/apicurio/registry/storage/impl/sql/MySqlRegistryStorageProvider.java
  storage/mysql/src/main/resources/overlay.properties
  storage/mysql/src/test/java/io/apicurio/registry/storage/impl/sql/MySqlRegistryStorageTest.java
  storage/mysql/src/test/java/io/apicurio/registry/storage/util/MySqlEmbeddedTestResource.java
  storage/mysql/src/test/java/io/apicurio/registry/storage/util/MySqlStorageTestResources.java
  storage/mysql/src/test/resources/test-overlay.properties
Labels: area/storage, area/rules

#3726 fix: Build for MySQL Registry Storage
  CONTRIBUTING.md
  Makefile
  README.md
  TESTING.md
  distro/docker/pom.xml
  srcclr.yml
Labels: area/ui, area/storage
