Repository Apicurio/apicurio-registry, pull requests merged in 2024-10, with the labels that each got.

#5291 [2.5] Upgrade Avro to 1.11.4
  pom.xml
Labels: triage/needs-triage

#5293 [2.6] Upgrade Avro to 1.11.4
  pom.xml
Labels: triage/needs-triage

#5289 Restore the "Generate Client SDK" feature in the UI
  ui/ui-app/.gitignore
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/public/client-gen/.gitignore
  ui/ui-app/public/client-gen/client-gen.js
  ui/ui-app/src/app/components/modals/GenerateClientModal.tsx
  ui/ui-app/src/app/components/modals/index.ts
  ui/ui-app/src/app/pages/version/VersionPage.tsx
  ui/ui-app/src/app/pages/version/components/tabs/VersionInfoTabContent.tsx
  ui/ui-app/src/services/useDownloadService.ts
Labels: area/ui

#5300 Upgrade a few dependencies
  app/src/test/java/io/apicurio/registry/noprofile/rest/v2/ConcurrentCreateTest.java
  common/pom.xml
  pom.xml
  utils/exportConfluent/pom.xml
  utils/exportV1/pom.xml
Labels: triage/needs-triage

#5316 Add useful information to the authentication error
  app/src/main/java/io/apicurio/registry/rest/AuthenticationFailedExceptionMapper.java
  app/src/main/java/io/apicurio/registry/rest/RegistryExceptionMapper.java
  app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
Labels: area/rest-api

#5310 fix download link
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: triage/needs-triage

#5315 Port json schema objects, asyncapi and openapi dereferencing
  docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/ApicurioDataModelsContentDereferencer.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/ReferenceInliner.java
  schema-util/util-provider/pom.xml
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/dereference/JsonSchemaContentDereferencerTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/dereference/OpenApiContentDereferencerTest.java
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/address.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/all-types.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/expected-testDereference-object-level-json.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/expected-testDereference-openapi.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/expected-testDereference-property-level-json.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/json-schema-to-deref-object-level.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/json-schema-to-deref-property-level.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/openapi-to-deref.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/types/all-types.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/types/city/qualification.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/types/identifier/qualification.json
Labels: triage/needs-triage

#5323 Changed example from readme
  README.md
Labels: triage/needs-triage

#5321 [2.6.x] Added a productization profile with dep verifier
  pom.xml
  prod-verifier/pom.xml
Labels: triage/needs-triage

#5274 Add artifact created event based on the outbox pattern
  app/src/main/java/io/apicurio/registry/events/ArtifactCreated.java
  app/src/main/java/io/apicurio/registry/events/ArtifactDeleted.java
  app/src/main/java/io/apicurio/registry/events/ArtifactMetadataUpdated.java
  app/src/main/java/io/apicurio/registry/events/ArtifactRuleConfigured.java
  app/src/main/java/io/apicurio/registry/events/ArtifactVersionCreated.java
  app/src/main/java/io/apicurio/registry/events/ArtifactVersionDeleted.java
  app/src/main/java/io/apicurio/registry/events/ArtifactVersionMetadataUpdated.java
  app/src/main/java/io/apicurio/registry/events/GlobalRuleConfigured.java
  app/src/main/java/io/apicurio/registry/events/GroupCreated.java
  app/src/main/java/io/apicurio/registry/events/GroupDeleted.java
  app/src/main/java/io/apicurio/registry/events/GroupMetadataUpdated.java
  app/src/main/java/io/apicurio/registry/events/GroupRuleConfigured.java
  app/src/main/java/io/apicurio/registry/rest/v3/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/StorageEventType.java
  app/src/main/java/io/apicurio/registry/storage/decorator/ReadOnlyRegistryStorageDecorator.java
  app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecoratorBase.java
  app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecoratorReadOnlyBase.java
  app/src/main/java/io/apicurio/registry/storage/dto/AggregateType.java
  app/src/main/java/io/apicurio/registry/storage/dto/OutboxEvent.java
  app/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlConfiguration.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlEventsProcessor.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlOutboxEvent.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlEventsProcessor.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlOutboxEvent.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/resources/application.properties
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/db-version
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/mssql.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/h2.upgrade.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/mssql.upgrade.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/postgresql.upgrade.ddl
  app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
  app/src/test/java/io/apicurio/registry/event/kafkasql/KafkaSqlEventsTest.java
  app/src/test/java/io/apicurio/registry/event/kafkasql/KafkaSqlEventsTestProfile.java
  app/src/test/java/io/apicurio/registry/event/sql/EventsTestProfile.java
  app/src/test/java/io/apicurio/registry/event/sql/RegistryEventsTest.java
  app/src/test/java/io/apicurio/registry/storage/impl/readonly/ReadOnlyRegistryStorageTest.java
  common/src/main/java/io/apicurio/registry/events/dto/RegistryEventType.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-config-migration.adoc
  integration-tests/src/test/resources/infra/kafka/kafka.yml
  integration-tests/src/test/resources/infra/kafka/registry-kafka.yml
  pom.xml
  utils/tests/pom.xml
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/DebeziumContainerResource.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/KafkaTestContainerManager.java
Labels: area/rest-api, area/storage

#5335 Fixed some of the "available since" info for our config properties (for 3.0.0) config
  app/src/main/java/io/apicurio/registry/auth/AuthConfig.java
  app/src/main/java/io/apicurio/registry/storage/RegistryStorageProducer.java
  app/src/main/java/io/apicurio/registry/storage/impl/gitops/BlueDatasourceProducer.java
  app/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/gitops/GreenDatasourceProducer.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryDatasourceProducer.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
Labels: area/storage

#5336 Update SerdeConfig reference
  docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
Labels: triage/needs-triage

#5349 Upgraded Kiota to 1.19.1
  go-sdk/go-sdk.csproj
  go-sdk/pkg/registryclient-v2/ids/content_hashes_item_with_content_hash_request_builder.go
  go-sdk/pkg/registryclient-v2/ids/content_hashes_request_builder.go
  go-sdk/pkg/registryclient-v2/ids/content_hashes_with_content_hash_item_request_builder.go
  go-sdk/pkg/registryclient-v2/ids/content_ids_item_with_content_id_request_builder.go
  go-sdk/pkg/registryclient-v2/ids/content_ids_request_builder.go
  go-sdk/pkg/registryclient-v2/ids/content_ids_with_content_item_request_builder.go
  go-sdk/pkg/registryclient-v2/kiota-lock.json
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  java-sdk/pom.xml
  python-sdk/python-sdk.csproj
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/package-lock.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
Labels: area/ui

#5350 Restore storage test [updated]
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/mssql.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/h2.upgrade.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/mssql.upgrade.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/postgresql.upgrade.ddl
  app/src/test/java/io/apicurio/registry/noprofile/storage/AbstractRegistryStorageTest.java
  app/src/test/java/io/apicurio/registry/storage/impl/sql/DefaultRegistryStorageTest.java
Labels: area/storage

#5358 Fix ui tests
  ui/tests/specs/settings.spec.ts
Labels: area/ui

#5359 Pass reference rewrites between recursive calls
  app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryContentUtils.java
  examples/json-maven-with-references-auto/pom.xml
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIBusinessUnitBaseTypes.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIItemBaseTypes.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIMessageHeader.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIServiceTypes.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIStockAdjustment.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIStockTypes.json
  examples/pom.xml
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: area/storage, port-3.x

#5365 Move spotless to a profile so it can be disabled
  pom.xml
Labels: triage/needs-triage

#5370 Bump kiota community
  java-sdk-v2/pom.xml
  java-sdk/pom.xml
Labels: triage/needs-triage

#5363 Add a basic Sql Datasource for operator
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/SqlDatasourceITTest.java
  operator/controller/src/test/resources/k8s/example-postgres.yaml
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/ApicurioRegistry3SpecApp.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/Sql.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/sql/Datasource.java
Labels: area/storage

#5376 Add modifiedBy and modifiedOn to version metadata
  app/src/main/java/io/apicurio/registry/rest/v3/V3ApiUtil.java
  app/src/main/java/io/apicurio/registry/storage/dto/ArtifactVersionMetaDataDto.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ArtifactVersionMetaDataDtoMapper.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/VersionModifiedByOnTest.java
  common/src/main/resources/META-INF/openapi.json
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  go-sdk/pkg/registryclient-v3/models/version_meta_data.go
Labels: area/rest-api, area/storage

#5386 Expose more Kiota knobs to ease the build of the SDKs
  java-sdk-v2/pom.xml
  java-sdk/pom.xml
  pom.xml
Labels: area/ui

#5385 feat(REST API): Added labels to all search results
  app/src/main/java/io/apicurio/registry/rest/RestConfig.java
  app/src/main/java/io/apicurio/registry/rest/v3/V3ApiUtil.java
  app/src/main/java/io/apicurio/registry/storage/dto/SearchedArtifactDto.java
  app/src/main/java/io/apicurio/registry/storage/dto/SearchedGroupDto.java
  app/src/main/java/io/apicurio/registry/storage/dto/SearchedVersionDto.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/SearchedArtifactMapper.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/SearchedGroupMapper.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/SearchedVersionMapper.java
  app/src/main/resources/application.properties
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/CappedLabelsInSearchResultsTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/SearchArtifactsTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/SearchGroupsTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/SearchVersionsTest.java
  common/src/main/resources/META-INF/openapi.json
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  go-sdk/pkg/registryclient-v3/models/searched_artifact.go
  go-sdk/pkg/registryclient-v3/models/searched_group.go
  go-sdk/pkg/registryclient-v3/models/searched_version.go
  pom.xml
Labels: area/rest-api, area/storage

#5395 feat(REST API): Allow additional orderBy options when searching
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  common/src/main/resources/META-INF/openapi.json
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  go-sdk/pkg/registryclient-v3/models/artifact_sort_by.go
  go-sdk/pkg/registryclient-v3/models/group_sort_by.go
  go-sdk/pkg/registryclient-v3/models/version_sort_by.go
Labels: area/rest-api, area/storage

#5402 fix(REST): Fix a problem where getVersionMetaData API operation was incorrectly returning `modifiedOn`
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ArtifactVersionMetaDataDtoMapper.java
Labels: area/storage

#5418 chore(UI): Improved UI build by using workspaces to link ui-app to typescript-sdk
  .github/workflows/integration-tests.yaml
  .github/workflows/release-images.yaml
  .github/workflows/release-sdk-typescript.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  typescript-sdk/README.md
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/package-lock.json
  ui/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
  utils/exportConfluent/pom.xml
Labels: area/ui

#5411 Support for MySQL storage
  .mvn/wrapper/maven-wrapper.properties
  app/pom.xml
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/MySQLSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryDatabaseKind.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatementsProducer.java
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/mysql.ddl
  app/src/main/resources/io/apicurio/registry/storage/impl/sql/upgrades/101/mysql.upgrade.ddl
  app/src/test/java/io/apicurio/registry/storage/impl/sql/MysqlStorageTest.java
  app/src/test/java/io/apicurio/registry/storage/util/MysqlTestProfile.java
  utils/tests/pom.xml
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/MySqlEmbeddedTestResource.java
Labels: area/storage

#5421 chore(UI build): Removed a UI file dependency that was not needed
  ui/package-lock.json
  ui/package.json
Labels: area/ui

#5424 chore(UI build): Upgraded all npm dependencies
  .github/dependabot.yml
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/package-lock.json
  ui/package.json
  ui/tests/package-lock.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
Labels: area/ui

#5429 fix(REST API): Implement the artifactId filter when searching artifacts
  app/src/main/java/io/apicurio/registry/rest/v3/SearchResourceImpl.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
Labels: area/rest-api, area/storage

#5409 [chore] cleanup sql datasource
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/KafkaSql.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/PostgresSql.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
Labels: area/storage

#5433 chore(UI build): Fix/typescript sdk package lock
  typescript-sdk/package-lock.json
  ui/tests/package-lock.json
  ui/tests/package.json
Labels: area/ui, area/rest-api, area/storage

#5436 feat(UI config): Added "draftMutability" to the UI config
  app/src/main/java/io/apicurio/registry/rest/v3/SystemResourceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/DraftContentTest.java
  common/src/main/resources/META-INF/openapi.json
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  go-sdk/pkg/registryclient-v3/models/user_interface_config_features.go
Labels: area/ui, area/rest-api

#5413 Add manual example for json schema refs
  examples/json-maven-with-references/pom.xml
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIBusinessUnitBaseTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIItemBaseTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIMessageHeader.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIServiceTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIStockTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/out/jsd/FLIStockAdjustment.json
  examples/pom.xml
  schema-util/json/src/main/java/io/apicurio/registry/content/dereference/JsonSchemaDereferencer.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: port-3.x, 2.6.x

#5445 feat(UI): The UI now has better support for being served from a context path
  ui/.docker-scripts/entrypoint.sh
  ui/.docker-scripts/update-base-href.cjs
  ui/Dockerfile
  ui/deploy-examples/build-container-image.sh
  ui/deploy-examples/getting-started-context-path/docker-compose.yml
  ui/deploy-examples/getting-started-context-path/nginx.conf
  ui/deploy-examples/getting-started/docker-compose.yml
  ui/ui-app/index.html
  ui/ui-app/package-lock.json
  ui/ui-app/src/app/components/header/AppHeader.tsx
  ui/ui-app/src/app/components/header/AppHeaderToolbar.tsx
  ui/ui-app/src/app/components/header/AvatarDropdown.tsx
  ui/ui-app/src/app/components/modals/GenerateClientModal.tsx
  ui/ui-app/vite.config.mts
Labels: area/ui
