Repository Apicurio/apicurio-registry, pull requests merged in 2024-07, with the labels that each got.

#4857 Update examples using Docker Compose
  examples/docker-compose/README.md
  examples/event-driven-architecture/README.md
  examples/event-driven-architecture/docker-compose.yml
Labels: area/documentation

#4847 Nginx returns SPA when trying to access an API version containing a period
  ui/.docker-scripts/nginx.conf
Labels: area/ui

#4881 Upgraded kiota and react dependencies
  typescript-sdk/package.json
  ui/package-lock.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
Labels: area/ui

#4885 fix: override version of io.strimzi:kafka-oauth-common
  pom.xml
Labels: triage/needs-triage

#4888 Fix searchVersions Method when used in ApiCurio 3.0.0.M3 with mssql as storage layer
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
Labels: area/storage

#4886 Inherit the strimzi oauth dep from quarkus
  pom.xml
Labels: area/dependencies, 3.x

#4892 Enable access logs by default
  app/src/main/resources/application.properties
Labels: triage/needs-triage

#4902 Ensure inappropiate actions are hidden in UI read-only mode
  app/src/main/java/io/apicurio/registry/rules/integrity/IntegrityRuleExecutor.java
  ui/ui-app/src/app/pages/artifact/components/tabs/BranchesTable.tsx
  ui/ui-app/src/app/pages/artifact/components/tabs/VersionsTable.tsx
  ui/ui-app/src/app/pages/explore/components/toolbar/ExplorePageToolbar.tsx
  ui/ui-app/src/services/useConfigService.ts
Labels: area/ui, area/rules

#4920 Update pyproject.toml
  python-sdk/pyproject.toml
Labels: triage/needs-triage

#4929 Close result set using try with resources
  app/src/main/java/io/apicurio/registry/storage/impl/sql/jdb/MappedQueryImpl.java
Labels: area/storage

#4935 Code formatting for MappedQueryImpl
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/jdb/MappedQueryImpl.java
Labels: area/storage

#4953 Group level rules
  app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v3/AdminResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v3/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/rules/RulesProperties.java
  app/src/main/java/io/apicurio/registry/rules/RulesPropertiesImpl.java
  app/src/main/java/io/apicurio/registry/rules/RulesServiceImpl.java
  app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/decorator/ReadOnlyRegistryStorageDecorator.java
  app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecoratorBase.java
  app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecoratorReadOnlyBase.java
  app/src/main/java/io/apicurio/registry/storage/impl/gitops/AbstractReadOnlyRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/messages/CreateArtifactRule4Message.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/messages/CreateGroupRule3Message.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/messages/DeleteGroupRule2Message.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/messages/DeleteGroupRules1Message.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/messages/ImportGroupRule1Message.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/messages/UpdateGroupRule3Message.java
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/serde/KafkaSqlMessageIndex.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/GroupRuleEntityMapper.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/GroupRulesTest.java
  app/src/test/java/io/apicurio/registry/noprofile/validity/ValidityRuleApplicationTest.java
  app/src/test/java/io/apicurio/registry/storage/impl/readonly/ReadOnlyRegistryStorageTest.java
  common/src/main/resources/META-INF/openapi.json
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_rules_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_rules_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_rules_with_rule_type_item_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/with_group_item_request_builder.go
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  ui/ui-app/src/app/components/ruleList/RuleList.tsx
  ui/ui-app/src/app/components/ruleList/RuleListType.ts
  ui/ui-app/src/app/components/ruleList/RuleValue.tsx
  ui/ui-app/src/app/components/ruleList/index.ts
  ui/ui-app/src/app/pages/artifact/components/tabs/ArtifactInfoTabContent.tsx
  ui/ui-app/src/app/pages/group/GroupPage.tsx
  ui/ui-app/src/app/pages/group/components/tabs/GroupInfoTabContent.tsx
  ui/ui-app/src/app/pages/rules/RulesPage.tsx
  ui/ui-app/src/services/useGroupsService.ts
  utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/EntityType.java
  utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/GroupRuleEntity.java
Labels: area/rest-api, area/storage, area/rules
