Repository Apicurio/apicurio-registry, pull requests merged in 2024-12, with the labels that each got.

#5577 Upgrade avro version
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentClientV7Test.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
  pom.xml
  schema-util/avro/src/main/java/io/apicurio/registry/rules/compatibility/AvroCompatibilityChecker.java
  schema-util/avro/src/main/java/io/apicurio/registry/rules/validity/AvroContentValidator.java
  serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaUtils.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AvroDirectoryParser.java
  utils/tests/pom.xml
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/BaseHttpUtils.java
Labels: area/serdes, area/rules

#5630 fix(operator): use a correct tag in the install file, other small fixes
  .github/workflows/operator.yaml
  operator/README.md
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/PostgresSql.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/SqlDataSourceITTest.java
  operator/install/install.yaml
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/Sql.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/sql/DataSource.java
Labels: area/storage

#5639 Remove unused kotlinx-serialization dependency
  pom.xml
  utils/protobuf-schema-utilities/pom.xml
Labels: triage/needs-triage

#5637 Fix cache hit avro data
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroDataSchemaCacheKey.java
  utils/converter/src/test/java/io/apicurio/registry/utils/converter/avro/AvroDataTest.java
Labels: triage/needs-triage, port-3.x

#5635 Fix non-owner can update artifact
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
  app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
Labels: area/rest-api, port-3.x

#5638 Fix incorrect orElse usage
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
Labels: triage/needs-triage

#5640 Upgrade dependencies
  pom.xml
Labels: triage/needs-triage

#5674 fix(import): Fix an issue where migrating from v2 to v3 failed to create the "latest" branch
  app/src/main/java/io/apicurio/registry/storage/importing/v2/SqlDataUpgrader.java
  app/src/test/java/io/apicurio/registry/DataUpgradeTest.java
  utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/EntityReader.java
Labels: area/storage

#5676 fix(vertx-client): Make sure to close the Vertx instance in the maven plugin
  app/pom.xml
  app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
  app/src/test/java/io/apicurio/registry/auth/AuthTestAnonymousCredentials.java
  app/src/test/java/io/apicurio/registry/auth/AuthTestAuthenticatedReadAccess.java
  app/src/test/java/io/apicurio/registry/auth/AuthTestLocalRoles.java
  app/src/test/java/io/apicurio/registry/auth/AuthTestNoRoles.java
  app/src/test/java/io/apicurio/registry/auth/AuthTestProfileBasicClientCredentials.java
  app/src/test/java/io/apicurio/registry/auth/BasicAuthWithPropertiesTest.java
  app/src/test/java/io/apicurio/registry/auth/HeaderRoleSourceTest.java
  app/src/test/java/io/apicurio/registry/auth/MojoAuthTest.java
  app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
  app/src/test/java/io/apicurio/registry/noprofile/resolver/SchemaResolverTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/impexp/ExportLoader.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroPulsarSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
  app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java
  docs/modules/ROOT/partials/getting-started/proc-writing-registry-sdk.adoc
  examples/custom-strategy/src/main/java/io/apicurio/registry/examples/custom/strategy/CustomStrategyExample.java
  examples/jsonschema-validation/src/main/java/io/apicurio/registry/examples/validation/json/JsonSchemaValidationExample.java
  examples/protobuf-bean/src/main/java/io/apicurio/registry/examples/simple/protobuf/ProtobufBeanExample.java
  examples/protobuf-find-latest/src/main/java/io/apicurio/registry/examples/simple/protobuf/ProtobufFindLatestExample.java
  examples/protobuf-validation/src/main/java/io/apicurio/registry/examples/validation/protobuf/ProtobufValidationExample.java
  examples/rest-client/src/main/java/io/apicurio/registry/examples/RegistryLoader.java
  examples/rest-client/src/main/java/io/apicurio/registry/examples/SimpleRegistryDemo.java
  examples/rest-client/src/main/java/io/apicurio/registry/examples/SimpleRegistryDemoBasicAuth.java
  examples/rest-client/src/main/java/io/apicurio/registry/examples/util/RegistryDemoUtil.java
  examples/serdes-with-references/src/main/java/io/apicurio/registry/examples/references/JsonSerdeReferencesExample.java
  examples/simple-avro-maven/src/main/java/io/apicurio/registry/examples/simple/avro/maven/SimpleAvroMavenExample.java
  examples/simple-json/src/main/java/io/apicurio/registry/examples/simple/json/SimpleJsonSchemaExample.java
  examples/simple-protobuf/src/main/java/io/apicurio/registry/examples/simple/protobuf/SimpleProtobufExample.java
  examples/simple-validation/src/main/java/io/apicurio/registry/examples/simple/json/MessageValidator.java
  examples/simple-validation/src/main/java/io/apicurio/registry/examples/simple/json/SimpleValidationExample.java
  integration-tests/src/test/java/io/apicurio/deployment/KafkaSqlDeploymentManager.java
  integration-tests/src/test/java/io/apicurio/tests/ApicurioRegistryBaseIT.java
  integration-tests/src/test/java/io/apicurio/tests/auth/SimpleAuthIT.java
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/DataMigrationIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/DoNotPreserveIdsImportIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/GenerateCanonicalHashImportIT.java
  integration-tests/src/test/java/io/apicurio/tests/utils/LimitingProxy.java
  java-sdk/pom.xml
  java-sdk/src/main/java/io/apicurio/registry/client/auth/VertXAuthFactory.java
  utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/EntityReader.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/DownloadRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/TestUpdateRegistryMojo.java
Labels: area/storage

#5675 fix(db): New config property to set the name of the db schema
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/MySQLSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/main/resources/application.properties
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
Labels: area/storage

#5684 fix typo in env var name
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-kafka-storage.adoc
Labels: area/storage

#5685 Fix vertx failures in the maven plugin
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/DownloadRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/TestUpdateRegistryMojo.java
Labels: triage/needs-triage

#5690 fix(maven): Improved maven plugin output on failure
  app/src/main/java/io/apicurio/registry/services/http/CoreRegistryExceptionMapperService.java
  schema-util/common/src/main/java/io/apicurio/registry/rules/RuleViolationException.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/TestUpdateRegistryMojo.java
Labels: area/rules

#5691 chore(kiota): Upgrade/kiota 1.21.0
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  go-sdk/pkg/registryclient-v2/kiota-lock.json
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  pom.xml
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
Labels: area/ui
