Repository Apicurio/apicurio-registry, pull requests merged in 2024-03, with the labels that each got.

#4272 Implement derefence proto
  app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
  docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
  schema-util/protobuf/src/main/java/io/apicurio/registry/content/dereference/ProtobufDereferencer.java
  serdes/protobuf-serde/src/main/java/io/apicurio/registry/serde/protobuf/ProtobufSchemaParser.java
  utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
Labels: area/ui, area/compatibility, area/rest-api, area/storage, area/rules, area/rest-client

#4393 Use snapshot image for image scan
  .github/workflows/image-scan.yaml
Labels: triage/needs-triage

#4394 Add image scan for storage variants
  .github/workflows/image-scan.yaml
Labels: area/storage

#4416 Fix orphaned content not properly deleted
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentClientV7Test.java
Labels: area/storage

#4422 Dereference doc cleanup
  docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation

#4423 docs: clean up links and clarify dereference
  docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation

#4429 Use token to connect to pypi
  python-sdk/Makefile
Labels: triage/needs-triage

#4451 Upgrade quarkus version
  pom.xml
Labels: triage/needs-triage

#4464 Fix ccompat v6 legacy config
  app/src/main/java/io/apicurio/registry/ccompat/rest/v6/impl/SchemasResourceImpl.java
Labels: triage/needs-triage

#4470 [2.5.x] Set default log level for OIDC provider to DEBUG
  app/src/main/resources/application.properties
Labels: triage/needs-triage
