Repository Apicurio/apicurio-registry, pull requests merged in 2024-01, with the labels that each got.

#3913 Bump Kiota versions in Python SDK
  python-sdk/kiota-version.csproj
  python-sdk/poetry.lock
  python-sdk/pyproject.toml
Labels: triage/needs-triage

#4176 Bump Kiota and dependencies of the Python SDK
  python-sdk/kiota-version.csproj
  python-sdk/poetry.lock
  python-sdk/pyproject.toml
  python-sdk/tests/basic_test.py
Labels: triage/needs-triage

#4234 Use runtime image instead of build
  distro/docker/src/main/docker/Dockerfile.jvm
Labels: area/ui

#4235 Fix image scan workflow
  .github/workflows/image-scan.yaml
Labels: triage/needs-triage

#4236 Fix parameter name
  .github/workflows/image-scan.yaml
Labels: triage/needs-triage

#4237 Change base image to use the runtime
  distro/docker/src/main/docker/Dockerfile.jvm
  distro/docker/src/main/docker/Dockerfile.kafkasql.jvm
  distro/docker/src/main/docker/Dockerfile.mssql.jvm
  distro/docker/src/main/docker/Dockerfile.mysql.jvm
  distro/docker/src/main/docker/Dockerfile.sql.jvm
Labels: area/storage

#4180 Add service loader manifests for Kafka Connect Converters
  utils/converter/src/main/resources/META-INF/services/org.apache.kafka.connect.storage.Converter
Labels: area/storage

#4239 When UI is read-only, show Rule config as text
  ui/ui-app/configs/config-3scale.js
  ui/ui-app/configs/config-none.js
  ui/ui-app/configs/config-oidc-rbac.js
  ui/ui-app/configs/config-oidc.js
  ui/ui-app/src/app/components/header/RootPageHeader.tsx
  ui/ui-app/src/app/components/ruleList/CompatibilityLabel.tsx
  ui/ui-app/src/app/components/ruleList/IntegrityLabel.tsx
  ui/ui-app/src/app/components/ruleList/IntegritySelect.tsx
  ui/ui-app/src/app/components/ruleList/RuleList.css
  ui/ui-app/src/app/components/ruleList/RuleList.tsx
  ui/ui-app/src/app/components/ruleList/RuleValue.tsx
  ui/ui-app/src/app/components/ruleList/ValidityLabel.tsx
  ui/ui-app/src/app/components/ruleList/ValiditySelect.tsx
  ui/ui-app/src/app/components/ruleList/index.ts
  ui/ui-app/src/app/pages/artifactVersion/components/tabs/InfoTabContent.tsx
  ui/ui-app/src/app/pages/rules/RulesPage.tsx
Labels: area/ui, area/compatibility, area/rules

#4254 Bump Kiota in Python and Go SDKs
  go-sdk/generate.sh
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/kiota-version.csproj
  go-sdk/pkg/registryclient-v2/kiota-lock.json
  go-sdk/pkg/registryclient-v3/.kiota.log
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_branches_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_branches_with_branch_item_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_comments_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_comments_with_comment_item_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_meta_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_references_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_state_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_with_version_expression_item_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_with_artifact_item_request_builder.go
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  go-sdk/pkg/registryclient-v3/models/artifact_branch.go
  python-sdk/kiota-version.csproj
  python-sdk/poetry.lock
  python-sdk/pyproject.toml
Labels: triage/needs-triage

#4271 docs: minor edits to fix typos and formatting
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/shared/attributes-links.adoc
  docs/modules/ROOT/partials/shared/attributes.adoc
Labels: Documentation

#4264 chore: run go-sdk generation during maven build
  common/pom.xml
  go-sdk/Makefile
  go-sdk/generate-docker.sh
  go-sdk/generate.sh
Labels: area/ui

#4273 UI config now primarily pulled from backend endpoint
  app/src/main/java/io/apicurio/registry/rest/v3/SystemResourceImpl.java
  app/src/main/java/io/apicurio/registry/ui/UserInterfaceConfigProperties.java
  common/src/main/resources/META-INF/openapi.json
  docs/generateAllConfigPartial.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  ui/.docker-scripts/create-config.cjs
  ui/ui-app/README.md
  ui/ui-app/configs/config-3scale.js
  ui/ui-app/configs/config-local.js
  ui/ui-app/configs/config-none.js
  ui/ui-app/configs/config-oidc-rbac.js
  ui/ui-app/configs/config-oidc.js
  ui/ui-app/init-dev.sh
  ui/ui-app/src/app/App.tsx
  ui/ui-app/src/main.tsx
  ui/ui-app/src/services/useConfigService.ts
Labels: area/ui, area/rest-api
