Repository Apicurio/apicurio-registry, pull requests merged in 2024-11, with the labels that each got.

#5452 chore(UI deps): Upgrade all UI dependencies
  ui/tests/package-lock.json
  ui/tests/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/src/app/App.tsx
  ui/ui-app/src/app/components/header/AppHeader.tsx
  ui/ui-app/src/app/components/header/AppHeaderToolbar.tsx
  ui/ui-app/src/app/components/header/AvatarDropdown.tsx
  ui/ui-app/src/app/pages/404/404.tsx
  ui/ui-app/src/app/pages/PageProperties.ts
  ui/ui-app/src/app/pages/artifact/ArtifactPage.tsx
  ui/ui-app/src/app/pages/branch/BranchPage.tsx
  ui/ui-app/src/app/pages/explore/ExplorePage.tsx
  ui/ui-app/src/app/pages/group/GroupPage.tsx
  ui/ui-app/src/app/pages/index.ts
  ui/ui-app/src/app/pages/roles/RolesPage.tsx
  ui/ui-app/src/app/pages/root/RootRedirectPage.tsx
  ui/ui-app/src/app/pages/rules/RulesPage.tsx
  ui/ui-app/src/app/pages/settings/SettingsPage.tsx
  ui/ui-app/src/app/pages/version/VersionPage.tsx
  ui/ui-app/src/app/pages/version/components/tabs/ContentTabContent.tsx
  ui/ui-app/src/app/pages/version/components/tabs/DocumentationTabContent.tsx
  ui/ui-app/src/services/useArtifactTypesService.ts
  ui/ui-app/src/services/useConfigService.ts
  ui/ui-app/src/utils/content.utils.ts
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
Labels: area/ui, area/rules

#5364 [chore] Fix double start of operator in tests
  operator/controller/src/main/resources/application.properties
Labels: triage/needs-triage

#5446 update intro
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-artifact-version.png
  docs/modules/ROOT/assets/images/images/getting-started/registry-web-console-artifact.png
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
Labels: triage/needs-triage

#5470 Fixed a couple places where we were not URI encoding elements of nav links
  ui/ui-app/src/app/pages/artifact/ArtifactPage.tsx
  ui/ui-app/src/app/pages/group/GroupPage.tsx
Labels: area/ui

#5471 Added an option to the /ids/globalIds endpoint to return the artifacttype as a response header
  app/src/main/java/io/apicurio/registry/rest/v3/IdsResourceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/IdsResourceTest.java
  common/src/main/resources/META-INF/openapi.json
  go-sdk/pkg/registryclient-v3/ids/global_ids_with_global_item_request_builder.go
  go-sdk/pkg/registryclient-v3/kiota-lock.json
Labels: area/rest-api

#5472 Fix state change value
  app/src/main/java/io/apicurio/registry/events/ArtifactVersionStateChanged.java
Labels: triage/needs-triage

#5475 chore(UI): Upgrade nginx in UI docker image
  ui/Dockerfile
Labels: area/ui

#5476 feat(import): Create missing groups when importing
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/importing/v2/SqlDataUpgrader.java
Labels: area/storage

#5479 feat(kafka): Added a new config for the Kafka consumer group name
  app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java
Labels: area/storage

#5481 chore(UI): Upgrade UI dependencies
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
Labels: area/ui

#5480 chore(REST): Added a test for the /groups endpoint in case we did not have one yet
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/GroupsResourceTest.java
Labels: triage/needs-triage

#5483 Fix oidc docs
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security-azure.adoc
Labels: triage/needs-triage

#5490 Implement the defaultToGlobal option in ccompat /config/:subject endpoint
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/ConfigResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentCompatibilityConfigTest.java
Labels: area/compatibility

#5489 Fix operator tests flakiness in CI
  operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/KafkaSQLITTest.java
Labels: area/storage

#5497 chore(UI): Upgrade some dependencies
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
Labels: area/ui

#5487 Pass reference rewrites between recursive calls
  app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryContentUtils.java
  examples/json-maven-with-references-auto/pom.xml
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIBusinessUnitBaseTypes.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIItemBaseTypes.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIMessageHeader.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIServiceTypes.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIStockAdjustment.json
  examples/json-maven-with-references-auto/src/main/resources/schemas/FLIStockTypes.json
  examples/pom.xml
Labels: area/storage

#5499 Json maven deref test
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithAutoReferencesTest.java
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIBusinessUnitBaseTypes.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIItemBaseTypes.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIMessageHeader.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIServiceTypes.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIStockAdjustment.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIStockAdjustment_deref.json
  app/src/test/resources/io/apicurio/registry/noprofile/maven/stock/FLIStockTypes.json
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/dereference/JsonSchemaContentDereferencerTest.java
Labels: triage/needs-triage

#5222 Improvements on Nats Serdes
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/nats/AvroNatsSerdeIT.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumer.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumerImpl.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumerRecord.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumerRecordImpl.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/producers/NatsProducer.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/producers/NatsProducerImpl.java
Labels: area/serdes

#5501 chore(REST API Docs): Fixed some old, incorrect information in the openapi doc
  common/src/main/resources/META-INF/openapi.json
Labels: area/rest-api

#5508 chore(UI): Upgrade ui deps again
  .github/dependabot.yml
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
Labels: area/ui

#5509 feat(SDK): Add tests for the typescript SDK
  .github/workflows/integration-tests.yaml
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  typescript-sdk/tests/artifact.test.ts
  typescript-sdk/tests/group.test.ts
  typescript-sdk/tests/system-info.test.ts
  typescript-sdk/tests/test.utils.ts
  typescript-sdk/tsconfig.json
Labels: triage/needs-triage

#5512 chore(annotations): Reviewed annotations in the REST layer
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CompatibilityResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v3/AdminResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v3/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v3/IdsResourceImpl.java
Labels: area/rest-api

#5500 Add manual example for json schema refs
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  examples/json-maven-with-references/pom.xml
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIBusinessUnitBaseTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIItemBaseTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIMessageHeader.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIServiceTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/common/jsd/FLIStockTypes.json
  examples/json-maven-with-references/src/main/resources/schemas/out/jsd/FLIStockAdjustment.json
  examples/pom.xml
  schema-util/json/src/main/java/io/apicurio/registry/content/dereference/JsonSchemaDereferencer.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: triage/needs-triage

#5498 chore(Kiota): Upgraded Kiota from 1.19.1 to 1.20.0
  go-sdk/go-sdk.csproj
  go-sdk/pkg/registryclient-v2/kiota-lock.json
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  pom.xml
  python-sdk/python-sdk.csproj
  typescript-sdk/lib/sdk/factory.ts
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/src/app/components/modals/GenerateClientModal.tsx
Labels: area/ui

#5525 chore(typescript-sdk): Upgraded kiota-gen
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/ui-app/package-lock.json
Labels: area/ui

#5538 make example work
  common/src/main/resources/META-INF/openapi.json
Labels: triage/needs-triage

#5540 chore(deps): Removed wire-compiler
  pom.xml
  serdes/generic/serde-common-protobuf/pom.xml
  utils/protobuf-schema-utilities/pom.xml
Labels: area/serdes

#5546 chore(deps): Remove guava dependency where possible
  app/pom.xml
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  schema-util/avro/src/main/java/io/apicurio/registry/rules/compatibility/AvroCompatibilityChecker.java
  schema-util/avro/src/test/java/io/apicurio/registry/content/canon/AvroCompatibilityTest.java
  schema-util/avro/src/test/java/io/apicurio/registry/content/canon/TestAvroCompatibilityChecker.java
  schema-util/common/pom.xml
  schema-util/common/src/main/java/io/apicurio/registry/rules/compatibility/AbstractCompatibilityChecker.java
  schema-util/json/pom.xml
Labels: area/compatibility, area/rules

#5551 update env var docs for keycloak
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
Labels: triage/needs-triage

#5560 Fix array references rewrites
  schema-util/json/src/main/java/io/apicurio/registry/content/dereference/JsonSchemaDereferencer.java
  schema-util/json/src/main/java/io/apicurio/registry/content/refs/JsonSchemaReferenceFinder.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/dereference/JsonSchemaContentDereferencerTest.java
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/customer.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/expected-order-deref.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/order.json
Labels: triage/needs-triage, backport-2.x

#5561 Upgrade to quarkus 3.15
  app/pom.xml
  app/src/main/java/io/apicurio/registry/services/RegistryConfigSource.java
  app/src/main/resources/application-dev.properties
  app/src/main/resources/application-prod.properties
  pom.xml
Labels: triage/needs-triage

#5371 [2.6.x] Update keycloakjs and use access_token instead of id_token for oidc code path
  ui/package-lock.json
  ui/package.json
  ui/src/services/auth/auth.service.ts
Labels: area/ui

#5597 chore(operator): update default env. vars
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/EnvITTest.java
Labels: triage/needs-triage

#5608 chore(deps): Remove guava from all pom.xml files where it is not needed
  app/pom.xml
  pom.xml
  schema-util/json/pom.xml
Labels: triage/needs-triage

#5619 Remove apache http client
  pom.xml
  utils/tests/pom.xml
Labels: triage/needs-triage
