Repository Apicurio/apicurio-registry, pull requests merged in 2024-09, with the labels that each got.

#5105 Update refs examples docs
  docs/modules/ROOT/pages/getting-started/guide-exporting-registry-kafka-topic-data.adoc
  docs/modules/ROOT/partials/getting-started/con-kafka-connect-converters.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-avro.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-json.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-protobuf.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-types.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-in-memory-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-kafka-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-sql-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-migrating-registry-applications.adoc
  docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
Labels: area/storage

#5113 Update dependabot.yml
  .github/dependabot.yml
Labels: triage/needs-triage

#5126 Build Improvements
  app/pom.xml
  app/src/main/assembly/assembly.xml
  examples/protobuf-bean/pom.xml
  examples/protobuf-find-latest/pom.xml
  examples/protobuf-validation/pom.xml
  examples/serdes-with-references/pom.xml
  examples/simple-protobuf/pom.xml
  pom.xml
  serdes/protobuf-serde/pom.xml
  storage/kafkasql/src/main/assembly/assembly.xml
  storage/mssql/src/main/assembly/assembly.xml
  storage/mysql/src/main/assembly/assembly.xml
  storage/sql/src/main/assembly/assembly.xml
  utils/protobuf-schema-utilities/pom.xml
Labels: DO NOT MERGE

#5128 Java 11 compatible SDK
  java-sdk/pom.xml
Labels: triage/needs-triage

#5108 Stabilize CI pipelines
  .github/workflows/integration-tests.yaml
  .github/workflows/registry-rhbq-build.yaml
  .github/workflows/release-images.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  app/src/main/resources/application.properties
  integration-tests/pom.xml
  integration-tests/src/test/java/io/apicurio/deployment/RegistryDeploymentManager.java
  integration-tests/src/test/java/io/apicurio/tests/ApicurioRegistryBaseIT.java
  integration-tests/src/test/java/io/apicurio/tests/auth/SimpleAuthIT.java
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  integration-tests/src/test/java/io/apicurio/tests/kafkasql/KafkaSqlSnapshottingIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/DoNotPreserveIdsImportIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/JsonSchemaSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/ProtobufSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/SerdesTester.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/SimpleSerdesTesterBuilder.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredConsumerTesterBuilder.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredSerdesTesterBuilder.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
  integration-tests/src/test/resources/infra/kafka/kafka.yml
  integration-tests/src/test/resources/infra/kafka/registry-kafka.yml
  java-sdk-v2/pom.xml
  java-sdk/pom.xml
  pom.xml
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
  utils/importexport/pom.xml
Labels: triage/needs-triage

#5150 Upgraded to kiota 18 in the typescript sdk
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/package-lock.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/src/app/components/auth/IfAuth.tsx
  ui/ui-app/src/app/components/common/ArtifactDescription.tsx
  ui/ui-app/src/app/components/modals/CreateArtifactModal.tsx
  ui/ui-app/src/app/pages/artifact/components/tabs/BranchesTabToolbar.tsx
  ui/ui-app/src/app/pages/artifact/components/tabs/VersionsTabToolbar.tsx
  ui/ui-app/src/app/pages/branch/components/tabs/BranchVersionsTabToolbar.tsx
  ui/ui-app/src/app/pages/group/GroupPage.tsx
  ui/ui-app/src/app/pages/group/components/tabs/ArtifactsTabToolbar.tsx
  ui/ui-app/src/app/pages/roles/components/modals/GrantAccessModal.tsx
  ui/ui-app/src/app/pages/settings/components/ConfigProperty.tsx
  ui/ui-app/src/services/useUserService.ts
  ui/ui-app/src/utils/content.utils.ts
  ui/ui-app/src/utils/rest.utils.ts
Labels: area/ui

#5151 Upgrade the version of node used in the workflows
  .github/workflows/integration-tests.yaml
  .github/workflows/release-images.yaml
  .github/workflows/validate-openapi.yaml
Labels: triage/needs-triage

#5161 Upgraded kiota dependencies
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
Labels: area/ui

#5140 Config properties table
  app/src/main/java/io/apicurio/registry/auth/AuthConfig.java
  docs/modules/ROOT/pages/getting-started/assembly-config-reference.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-config-migration.adoc
Labels: Impacts Documentation, 3.x

#5180 [3.x] Concurrent artifact creation test & fixes
  app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/ConcurrentCreateTest.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java
Labels: area/storage

#5149 Change serdes use content id and 4 byte identifier
  app/src/test/java/io/apicurio/registry/noprofile/JsonSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-avro.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
  examples/confluent-serdes/src/main/java/io/apicurio/registry/examples/confluent/serdes/ConfluentSerdesExample.java
  examples/event-driven-architecture/README.md
  examples/event-driven-architecture/studio-connector.json
  integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/JsonSchemaSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/ProtobufSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/strategy/ArtifactReference.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaSerDe.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/Default4ByteIdHandler.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/Legacy8ByteIdHandler.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/BaseKafkaSerDeConfig.java
  serdes/serde-common/src/main/java/io/apicurio/registry/serde/headers/DefaultHeadersHandler.java
  serdes/serde-common/src/test/java/io/apicurio/registry/serde/headers/DefaultHeadersHandlerTest.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/CompactFormatStrategy.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/FormatStrategy.java
  utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/PrettyFormatStrategy.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java
Labels: area/serdes

#5189 [3.0] Forward port the "group concatenation" feature of the ccompat API introduced in 2.6.2
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/AbstractResource.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CCompatConfig.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CompatibilityResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectVersionsResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectsResourceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentCompatApiWithGroupsTest.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/CCompatWithGroupsTestProfile.java
Labels: area/compatibility

#5193 Implement simple avro pulsar serde
  app/pom.xml
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroPulsarSerdeTest.java
  integration-tests/pom.xml
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/KafkaSerdesTester.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/SimpleSerdesTesterBuilder.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredConsumerTesterBuilder.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredSerdesTesterBuilder.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/pulsar/AvroPulsarSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/pulsar/PulsarSerdesTester.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
  integration-tests/src/test/java/io/apicurio/tests/utils/PulsarFacade.java
  pom.xml
  serdes/pulsar/avro-serde/pom.xml
  serdes/pulsar/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroPulsarDeserializer.java
  serdes/pulsar/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroPulsarSerde.java
  serdes/pulsar/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroPulsarSerdeSchema.java
  serdes/pulsar/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroPulsarSerializer.java
  utils/tests/pom.xml
Labels: area/serdes

#5194 Fixed the UI config for settings
  ui/package-lock.json
  ui/ui-app/package-lock.json
  ui/ui-app/src/services/useConfigService.ts
Labels: area/ui

#5195 Implement nats avro serdes
  integration-tests/pom.xml
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/nats/AvroNatsSerdeIT.java
  pom.xml
  serdes/generic/serde-common-jsonschema/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaDeserializer.java
  serdes/kafka/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaDeserializer.java
  serdes/nats/avro-serde/pom.xml
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/exceptions/ApicurioNatsException.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumer.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumerImpl.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumerRecord.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/consumers/NatsConsumerRecordImpl.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/producers/NatsProducer.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/client/streaming/producers/NatsProducerImpl.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/config/NatsConsumerConfig.java
  serdes/nats/avro-serde/src/main/java/io/apicurio/registry/serde/avro/nats/config/NatsProducerConfig.java
Labels: area/serdes

#5199 Allow logout redirect URl to be configurable
  app/src/main/java/io/apicurio/registry/rest/v3/SystemResourceImpl.java
  app/src/main/java/io/apicurio/registry/ui/UserInterfaceConfigProperties.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  ui/.docker-scripts/create-config.cjs
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/src/app/App.tsx
  ui/ui-app/src/services/useConfigService.ts
Labels: area/ui, area/rest-api

#5212 Fix ids search
  app/src/main/java/io/apicurio/registry/storage/dto/SearchFilter.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/SearchVersionsTest.java
Labels: area/storage

#5223 Fix serializer dereference
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  serdes/generic/serde-common/src/main/java/io/apicurio/registry/serde/config/SerdeConfig.java
Labels: area/serdes

#5226 Update confluent export to be compatible with v3
  app/src/main/java/io/apicurio/registry/rest/v3/shared/DataExporter.java
  app/src/test/java/io/apicurio/registry/ConfluentDataMigrationTest.java
  app/src/test/java/io/apicurio/registry/DataUpgradeTest.java
  app/src/test/resources-unfiltered/io/apicurio/registry/upgrade/confluent-schema-registry-export.zip
  examples/tools/confluent-schema-registry/kafka-compose.yaml
  examples/tools/kafka-compose/kafka-compose.yaml
  integration-tests/src/test/java/io/apicurio/tests/migration/GenerateCanonicalHashImportIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/MigrationTestsDataInitializer.java
  utils/exportConfluent/README.md
  utils/exportConfluent/pom.xml
  utils/exportConfluent/src/main/java/io/apicurio/registry/utils/export/Export.java
  utils/exportConfluent/src/main/java/io/apicurio/registry/utils/export/ExportContext.java
  utils/exportConfluent/src/main/java/io/apicurio/registry/utils/export/mappers/ArtifactReferenceMapper.java
  utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/v2/EntityWriter.java
  utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/v3/EntityWriter.java
Labels: triage/needs-triage

#5240 Simplify serdes config by merging serde config and schema resolver co…
  app/src/test/java/io/apicurio/registry/noprofile/JsonSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/resolver/SchemaResolverTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-avro.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
  examples/debezium-openshift/src/main/java/io/apicurio/example/debezium/kafka/KafkaFactory.java
  examples/jsonschema-validation/src/main/java/io/apicurio/registry/examples/validation/json/JsonSchemaValidationExample.java
  examples/protobuf-validation/src/main/java/io/apicurio/registry/examples/validation/protobuf/ProtobufValidationExample.java
  examples/serdes-with-references/src/main/java/io/apicurio/registry/examples/references/JsonSerdeReferencesExample.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/AbstractConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/SchemaResolverConfig.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/strategy/ArtifactReferenceImpl.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/config/ConfigurationTest.java
  serdes/generic/serde-common/src/main/java/io/apicurio/registry/serde/SchemaResolverConfigurer.java
  serdes/generic/serde-common/src/main/java/io/apicurio/registry/serde/config/SerdeConfig.java
  serdes/kafka/serde-kafka-common/src/main/java/io/apicurio/registry/serde/config/BaseKafkaSerDeConfig.java
  serdes/kafka/serde-kafka-common/src/main/java/io/apicurio/registry/serde/headers/DefaultHeadersHandlerConfig.java
Labels: area/serdes

#5249 Adapt properties to required pattern
  app/src/main/java/io/apicurio/registry/metrics/health/liveness/PersistenceExceptionLivenessCheck.java
  app/src/main/java/io/apicurio/registry/metrics/health/liveness/ResponseErrorLivenessCheck.java
  app/src/main/java/io/apicurio/registry/metrics/health/readiness/PersistenceTimeoutReadinessCheck.java
  app/src/main/java/io/apicurio/registry/metrics/health/readiness/ResponseTimeoutReadinessCheck.java
  app/src/main/java/io/apicurio/registry/rest/RestConfig.java
  app/src/main/java/io/apicurio/registry/storage/importing/ImportExportConfigProperties.java
  app/src/main/resources/application-prod.properties
  app/src/main/resources/application-test.properties
  app/src/main/resources/application.properties
  app/src/test/java/io/apicurio/registry/noprofile/config/ConfigTest.java
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-config-migration.adoc
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/ApplicationRbacEnabledProfile.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/AuthTestProfile.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/BasicAuthWithPropertiesTestProfile.java
  utils/tests/src/main/java/io/apicurio/registry/utils/tests/DeletionEnabledProfile.java
Labels: area/rest-api, area/storage

#5250 Update serdes and examples documentation
  docs/modules/ROOT/pages/getting-started/guide-exporting-registry-kafka-topic-data.adoc
  docs/modules/ROOT/partials/getting-started/con-kafka-connect-converters.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-avro.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-json.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-protobuf.adoc
  docs/modules/ROOT/partials/getting-started/con-registry-serdes-types.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-in-memory-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-kafka-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-installing-registry-sql-storage.adoc
  docs/modules/ROOT/partials/getting-started/proc-migrating-registry-applications.adoc
  docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
  docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
Labels: area/storage, area/serdes

#5260 Fix wrong property name
  app/src/main/resources/application.properties
Labels: triage/needs-triage

#5259 feat: operator creates app and UI Services
  operator/controller/src/main/java/io/apicurio/registry/operator/ApicurioRegistry3Reconciler.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceFactory.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceKey.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppServiceDiscriminator.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppServiceResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ui/UIServiceDiscriminator.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ui/UIServiceResource.java
  operator/controller/src/main/resources/k8s/default/app.service.yaml
  operator/controller/src/main/resources/k8s/default/ui.service.yaml
  operator/controller/src/test/java/io/apicurio/registry/operator/it/SmokeITTest.java
Labels: area/ui

#5263 Update auth docs
  README.md
  docs/modules/ROOT/partials/getting-started/proc-configuring-kafka-oauth.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security-azure.adoc
  docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security-keycloak.adoc
  docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
  docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
  examples/docker-compose/src/main/resources/compose-base-mssql.yml
  examples/docker-compose/src/main/resources/compose-base-sql.yml
  examples/docker-compose/src/main/resources/docker-compose.apicurio.yml
  examples/event-driven-architecture/docker-compose.yml
  examples/openshift-template/apicurio-registry-template-sql.yml
  schema-resolver/src/main/java/io/apicurio/registry/resolver/config/SchemaResolverConfig.java
  schema-resolver/src/test/java/io/apicurio/registry/resolver/config/ConfigurationTest.java
Labels: area/storage

#5265 Fix oidc documentation
  docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
Labels: triage/needs-triage

#5272 Use graal to build native image and do not build it in docker
  .github/workflows/release-images.yaml
Labels: area/ui
