Repository Apicurio/apicurio-registry, pull requests merged in 2024-04, with the labels that each got.

#4504 Make it easier to change the kiota base url
  java-sdk/pom.xml
Labels: triage/needs-triage

#4471 [3.0.x] Set default log level for OIDC provider to DEBUG
  app/src/main/resources/application.properties
Labels: triage/needs-triage

#4540 Correct authorization level for config operation in ccompat
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
Labels: triage/needs-triage

#4528 Update 2.5 dependencies
  app/pom.xml
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  integration-tests/src/test/java/io/apicurio/deployment/RegistryDeploymentManager.java
  integration-tests/src/test/resources/infra/sql/postgresql.yml
  integration-tests/src/test/resources/infra/tenant-manager/tenant-manager-database.yml
  pom.xml
  utils/tests/pom.xml
Labels: triage/needs-triage

#4549 Fix as confluent documentation default value
  docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
Labels: triage/needs-triage

#4562 Use network nt library in the serdes for json schema
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/resources/io/apicurio/registry/util/citizen.json
  app/src/test/resources/io/apicurio/registry/util/citizenIdentifier.json
  app/src/test/resources/io/apicurio/registry/util/city.json
  app/src/test/resources/io/apicurio/registry/util/qualification.json
  app/src/test/resources/io/apicurio/registry/util/sample.account.json
  app/src/test/resources/io/apicurio/registry/util/sample.address.json
  app/src/test/resources/io/apicurio/registry/util/sample.email.json
  app/src/test/resources/io/apicurio/registry/util/sample.phone.json
  serdes/jsonschema-serde/pom.xml
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchema.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaDeserializer.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializer.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaParser.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaValidationUtil.java
Labels: area/serdes

#4563 Use network nt library in the serdes for json schema
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/resources/io/apicurio/registry/util/citizen.json
  app/src/test/resources/io/apicurio/registry/util/citizenIdentifier.json
  app/src/test/resources/io/apicurio/registry/util/city.json
  app/src/test/resources/io/apicurio/registry/util/qualification.json
  app/src/test/resources/io/apicurio/registry/util/sample.account.json
  app/src/test/resources/io/apicurio/registry/util/sample.address.json
  app/src/test/resources/io/apicurio/registry/util/sample.email.json
  app/src/test/resources/io/apicurio/registry/util/sample.phone.json
  pom.xml
  serdes/jsonschema-serde/pom.xml
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchema.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaDeserializer.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializer.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaParser.java
  serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaValidationUtil.java
Labels: area/serdes

#4571 Fix missing schema type
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectVersionsResourceImpl.java
Labels: triage/needs-triage

#4570 Fix missing schema type
  app/src/main/java/io/apicurio/registry/ccompat/rest/v6/impl/SubjectVersionsResourceImpl.java
  app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectVersionsResourceImpl.java
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v6/ConfluentCompatApiTest.java
  app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentCompatApiTest.java
Labels: triage/needs-triage

#4581 [REST API v3] Invert the metadata and content API endpoints for versions
  .github/workflows/verify.yaml
  app/.gitignore
  app/src/main/java/io/apicurio/registry/rest/v3/GroupsResourceImpl.java
  app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
  app/src/test/java/io/apicurio/registry/limits/LimitsTest.java
  app/src/test/java/io/apicurio/registry/noprofile/VersionStateTest.java
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithAutoReferencesTest.java
  app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithMinifyTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/CustomizeDateFormatTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/GroupsResourceTest.java
  app/src/test/java/io/apicurio/registry/noprofile/rest/v3/IdsResourceTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
  app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
  app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java
  app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java
  app/src/test/java/io/apicurio/registry/rest/DisableApisFlagsTest.java
  common/src/main/resources/META-INF/openapi.json
  examples/protobuf-bean/src/main/java/io/apicurio/registry/examples/simple/protobuf/ProtobufBeanExample.java
  examples/simple-avro-maven/src/main/java/io/apicurio/registry/examples/simple/avro/maven/SimpleAvroMavenExample.java
  examples/simple-protobuf/src/main/java/io/apicurio/registry/examples/simple/protobuf/SimpleProtobufExample.java
  examples/simple-validation/src/main/java/io/apicurio/registry/examples/simple/json/MessageValidator.java
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_content_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_item_meta_request_builder.go
  go-sdk/pkg/registryclient-v3/groups/item_artifacts_item_versions_with_version_expression_item_request_builder.go
  go-sdk/pkg/registryclient-v3/kiota-lock.json
  integration-tests/src/test/java/io/apicurio/tests/ApicurioRegistryBaseIT.java
  integration-tests/src/test/java/io/apicurio/tests/auth/SimpleAuthIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/DoNotPreserveIdsImportIT.java
  integration-tests/src/test/java/io/apicurio/tests/migration/GenerateCanonicalHashImportIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/ProtobufSerdeIT.java
  integration-tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
  integration-tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
  integration-tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
  integration-tests/src/test/java/io/apicurio/tests/utils/ArtifactUtils.java
  python-sdk/tests/basic_test.py
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
  ui/ui-app/src/services/useGroupsService.ts
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/DownloadRegistryMojo.java
  utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
Labels: area/rest-api

#4582 [chore] Java 21 compatibility
  docs/generateAllConfigPartial.java
  operator/model/pom.xml
  pom.xml
  utils/exportConfluent/pom.xml
Labels: area/compatibility

#4603 Beta support for inline dereferencing of OpenAPI and AsyncAPI
  app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
  app/src/main/java/io/apicurio/registry/rest/v2/IdsResourceImpl.java
  app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryContentUtils.java
  docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
  schema-util/common/src/main/java/io/apicurio/registry/content/dereference/ContentDereferencer.java
  schema-util/common/src/main/java/io/apicurio/registry/content/refs/JsonPointerExternalReference.java
  schema-util/json/src/main/java/io/apicurio/registry/content/dereference/JsonSchemaDereferencer.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/ApicurioDataModelsContentDereferencer.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/ReferenceInliner.java
  schema-util/openapi/src/main/java/io/apicurio/registry/content/dereference/ReferenceRewriter.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/ArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AsyncApiArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AvroArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/GraphQLArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/JsonArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/KConnectArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/OpenApiArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/ProtobufArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/WsdlArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/XmlArtifactTypeUtilProvider.java
  schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/XsdArtifactTypeUtilProvider.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/dereference/JsonSchemaContentDereferencerTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/content/dereference/OpenApiContentDereferencerTest.java
  schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/ArtifactUtilProviderTestBase.java
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/address.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/all-types.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/expected-testDereference-json.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/expected-testDereference-openapi.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/json-schema-to-deref.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/openapi-to-deref.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/types/all-types.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/types/city/qualification.json
  schema-util/util-provider/src/test/resources/io/apicurio/registry/content/dereference/types/identifier/qualification.json
Labels: area/rest-api, area/storage
