Repository Apicurio/apicurio-registry, pull requests merged in 2025-03, with the labels that each got.

#6051 Remove Studio and API Controller support from the operator
  .github/workflows/release-operator.yaml
  .github/workflows/release.yaml
  operator/Makefile
  operator/README.md
  operator/controller/src/main/deploy/api-controller-csv/apicurio-api-controller.clusterserviceversion.yaml
  operator/controller/src/main/deploy/api-controller-csv/kustomization.yaml
  operator/controller/src/main/deploy/api-controller-examples/example-registry-with-studio.apicurioregistry3.yaml
  operator/controller/src/main/deploy/api-controller-examples/kustomization.yaml
  operator/controller/src/main/deploy/operator/kustomization.yaml
  operator/controller/src/main/java/io/apicurio/registry/operator/ApicurioRegistry3Reconciler.java
  operator/controller/src/main/java/io/apicurio/registry/operator/Configuration.java
  operator/controller/src/main/java/io/apicurio/registry/operator/EnvironmentVariables.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/Cors.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ActivationConditions.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/LabelDiscriminators.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceFactory.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceKey.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIIngressResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUINetworkPolicyResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIPodDisruptionBudgetResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIServiceResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/updater/IngressCRUpdater.java
  operator/controller/src/main/java/io/apicurio/registry/operator/utils/IngressUtils.java
  operator/controller/src/main/resources/application.properties
  operator/controller/src/main/resources/k8s/default/studio-ui.ingress.yaml
  operator/controller/src/main/resources/k8s/default/studio-ui.networkpolicy.yaml
  operator/controller/src/main/resources/k8s/default/studio-ui.poddisruptionbudget.yaml
  operator/controller/src/main/resources/k8s/default/studio-ui.service.yaml
  operator/controller/src/test/java/io/apicurio/registry/operator/it/CRUpdateITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/EnvITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/NetworkPolicyITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/PodDisruptionBudgetITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/StudioSmokeITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/PodTemplateSpecArgumentProviders.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/PodTemplateSpecTest.java
  operator/controller/src/test/resources/k8s/examples/simple-with-studio-deprecated.apicurioregistry3.yaml
  operator/controller/src/test/resources/k8s/examples/simple-with-studio.apicurioregistry3.yaml
  operator/controller/src/test/resources/podtemplatespec-test-cases-studio-ui-negative.yaml
  operator/controller/src/test/resources/podtemplatespec-test-cases-studio-ui-positive.yaml
  operator/install/install.yaml
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/ApicurioRegistry3Spec.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/ContainerNames.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/StudioUiSpec.java
  operator/olm-tests/src/test/deploy/api-controller-catalog/catalog-source.yaml
  operator/olm-tests/src/test/deploy/api-controller-catalog/catalog.template.yaml
  operator/olm-tests/src/test/deploy/api-controller-catalog/operator-group.yaml
  operator/olm-tests/src/test/deploy/api-controller-catalog/subscription.yaml
Labels: version/3.x, area/operator

#5933 feat(operator): Support for JAVA_OPTS_APPEND when creating app deployment
  operator/controller/src/main/java/io/apicurio/registry/operator/EnvironmentVariables.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/utils/JavaOptsAppend.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/JavaOptsAppendTest.java
Labels: triage/needs-triage

#5955 Kafka auth support
  operator/controller/src/main/java/io/apicurio/registry/operator/EnvironmentVariables.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/KafkaSql.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/KafkaSqlAuth.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/KafkaSqlTLS.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/AuthITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/AuthTLSITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/AuthzITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/BaseAuthITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/BaseAuthTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/KafkaSqlITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/KafkaSqlOAuthITTest.java
  operator/controller/src/test/resources/k8s/examples/auth/authz-with_keycloak.apicurioregistry3.yaml
  operator/controller/src/test/resources/k8s/examples/auth/keycloak_http.yaml
  operator/controller/src/test/resources/k8s/examples/auth/keycloak_https.yaml
  operator/controller/src/test/resources/k8s/examples/auth/keycloak_realm.yaml
  operator/controller/src/test/resources/k8s/examples/auth/simple-with_keycloak.apicurioregistry3.yaml
  operator/controller/src/test/resources/k8s/examples/auth/tls/simple-with_keycloak.apicurioregistry3.yaml
  operator/controller/src/test/resources/k8s/examples/kafkasql/oauth/oauth-example-cluster.yaml
  operator/controller/src/test/resources/k8s/examples/kafkasql/oauth/oauth-example-kafkasql-tls.apicurioregistry3.yaml
  operator/install/install.yaml
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/KafkaSqlAuthSpec.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/KafkaSqlSpec.java
Labels: area/storage
