Repository Apicurio/apicurio-registry, pull requests merged in 2025-01, with the labels that each got.

#5774 chore(UI): Upgraded npm dependencies and fixed example deployment in UI
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/deploy-examples/getting-started-context-path/docker-compose.yml
  ui/tests/package-lock.json
  ui/tests/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-app/src/services/useConfigService.ts
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
Labels: area/ui

#5828 Fix pull requests slack notification
  .github/workflows/verify.yaml
Labels: triage/needs-triage

#5827 Allow passing the vertx instance to the serdes
  pom.xml
  schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
  schema-util/common/pom.xml
  serdes/generic/serde-common/pom.xml
  serdes/kafka/serde-kafka-common/pom.xml
  utils/kafka/pom.xml
  utils/tools/pom.xml
  utils/tools/src/main/java/io/apicurio/registry/utils/tools/AddOpenApiAuth.java
  utils/tools/src/main/java/io/apicurio/registry/utils/tools/TransformOpenApiForClientGen.java
  utils/tools/src/main/java/io/apicurio/registry/utils/tools/Transformer.java
  utils/tools/src/test/java/io/apicurio/registry/utils/tools/TransformerTest.java
Labels: area/serdes

#5841 chore(UI): Upgraded all npm dependencies again
  .github/dependabot.yml
  typescript-sdk/package-lock.json
  typescript-sdk/package.json
  ui/tests/package-lock.json
  ui/tests/package.json
  ui/ui-app/package-lock.json
  ui/ui-app/package.json
  ui/ui-docs/package-lock.json
  ui/ui-docs/package.json
Labels: area/ui

#5860 Upgrade quarkus to 3.15.3
  pom.xml
Labels: triage/needs-triage

#5880 Allow configure replicas
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceFactory.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/SmokeITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/StudioSmokeITTest.java
  operator/install/install.yaml
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/ComponentSpec.java
Labels: triage/needs-triage

#5898 feat(operator): New "features" section of the app spec to allow enabling deletes
  operator/.gitignore
  operator/controller/src/main/java/io/apicurio/registry/operator/EnvironmentVariables.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/AppFeaturesITTest.java
  operator/install/install.yaml
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/AppFeaturesSpec.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/AppSpec.java
Labels: triage/needs-triage

#5906 feat(operator): Add support for properly configuring the CORS allowed origins header
  operator/controller/src/main/java/io/apicurio/registry/operator/EnvironmentVariables.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/Cors.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceFactory.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/utils/IngressUtils.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/AppFeaturesITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/SmokeITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/CorsTest.java
  operator/controller/src/test/resources/k8s/examples/cors/example-default.yaml
  operator/controller/src/test/resources/k8s/examples/cors/example-env-vars-and-ingress.yaml
  operator/controller/src/test/resources/k8s/examples/cors/example-env-vars.yaml
  operator/controller/src/test/resources/k8s/examples/cors/example-ingress.yaml
Labels: triage/needs-triage

#5912 Default debug and test log level for Quarkus is now `INFO` instead of `DEBUG`
  operator/controller/src/main/resources/application.properties
Labels: triage/needs-triage

#5926 Add oidc scope configuration option
  app/src/main/java/io/apicurio/registry/ui/config/UiConfigProperties.java
  app/src/main/java/io/apicurio/registry/ui/servlets/ConfigJsServlet.java
  app/src/main/resources/application.properties
  docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
  ui/src/services/auth/auth.service.ts
Labels: port-3.x

#5935 Upgrade quarkus 3.15.3
  pom.xml
Labels: triage/needs-triage

#5938 refactor(operator): improve status conditions handling
  operator/controller/src/main/java/io/apicurio/registry/operator/ApicurioRegistry3Reconciler.java
  operator/controller/src/main/java/io/apicurio/registry/operator/StatusUpdater.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/StatusUpdaterTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/StatusUpdaterTest.java
Labels: triage/needs-triage

#5921 chore(operator): Operator workflow only runs when operator changes were made
  .github/workflows/operator.yaml
Labels: triage/needs-triage

#5940 chore(repo): Migrate from dependabot to renovate
  .github/dependabot.yml
  renovate.json
Labels: triage/needs-triage

#5950 chore(repo): Remove spotless
  .github/workflows/release-images.yaml
  .github/workflows/release-maven-artifacts.yaml
  .github/workflows/release-sboms.yaml
  operator/controller/src/main/java/io/apicurio/registry/operator/ApicurioRegistry3Reconciler.java
  operator/controller/src/main/java/io/apicurio/registry/operator/Configuration.java
  operator/controller/src/main/java/io/apicurio/registry/operator/feat/KafkaSqlTLS.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/LabelDiscriminators.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceFactory.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ResourceKey.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppIngressResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppServiceResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIIngressResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/studioui/StudioUIServiceResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ui/UIDeploymentResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ui/UIIngressResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/resource/ui/UIServiceResource.java
  operator/controller/src/main/java/io/apicurio/registry/operator/utils/SecretKeyRefTool.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/CRUpdateITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/EnvITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/IngressManager.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/PodTemplateSpecITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/SmokeITTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/it/StatusUpdaterTest.java
  operator/controller/src/test/java/io/apicurio/registry/operator/unit/PodTemplateSpecTest.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/spec/StorageType.java
  operator/model/src/main/java/io/apicurio/registry/operator/api/v1/status/ConditionStatus.java
  pom.xml
  schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffType.java
Labels: area/compatibility, area/storage, area/rules
